### ISSUE TITLE
Weak Ciphers and POODLE SSL3 issue

### ISSUE THREAD

**Issue by AmiSMB** [NagiosEnterprises/ncpa#100]
I am currently trying to go through PCI DSS Compliance and I really like this client for Nagios. The only issue that I have is that I have to hide it behind stunnel due to the fact that I am unable to change the ciphers that it uses so that it only uses high encryption and due to the POODLE vulnerability need to turn off SSLv2 and SSLv3 access. Can this be changed in the actual code to make this default?

**Comment by scot0357** [comment]
Fixed with merge https://github.com/NagiosEnterprises/ncpa/pull/122.

If you'd like to test the fix, my testing methodology was using this sh command:

`echo | timeout 3 openssl s_client -connect $1:5693 >/dev/null 2>&1; if [[ $? != 0 ]]; then echo "UNKNOWN: $1 timeout or connection error"; else echo | openssl s_client -connect $1:5693 -ssl3 2>&1 | grep -qo "sslv3 alert handshake failure\|SSL3_GET_RECORD:wrong version number" && echo "OK: $1 Not vulnerable" || echo "FAIL:  $1 vulnerable; sslv3 connection accepted"; fi`

**Comment by scot0357** [comment]
As a note for future readers (including myself), I having included the ability to specify SSLv2, SSLv3, TLSv1 as SSL versions to use. This is a new directive in the config. It defaults to TLSv1 if the inputted SSL version is invalid or non-existent. It now also logs SSL version used when the agent starts up.
