### ISSUE TITLE
CPU Usage Flapping at 100%

### ISSUE THREAD

**Issue by amachfx** [NagiosEnterprises/ncpa#101]
Monitored OS: Windows 2008 R2
Agent: NCPA 1.7.2
Service Check: CPU Usage
Issue: CPU Usage withing the agent and API flapping between 100% and 2% or 3%. Perfmon and Task manager showing that the CPU Usage is only 2% or 3% and never 100%. The monitored host is a VM with a single CPU.

**Comment by scot0357** [comment]
Yes, its taking the instantaneous CPU usage at that very moment, which is something I'd like to fix sooner rather than later. I'm looking to get 1.8 out the door, so I"m going to slate this for 1.9.0.

**Comment by ccztux** [comment]
Also affected system:
```
Linux tux.localdomain 2.6.18-404.el5 #1 SMP Tue Apr 7 12:42:54 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by krobertson71** [comment]
One way to offset this is to have the CPU rechecks set to 10 or 15.  This has been the standard at my current employer and my previous employer.  So the CPU check every minute would have to report passed your thresholds every time in order for an alert to go out.  Plus by having this set at a longer interval, it cuts down on the flapping.

**Comment by vAndrewJ** [comment]
This is a big problem for me with a large number of single vCPU VMs we run. htop showing absolutely nothing happening with CPU yet NCPA showing wild spikes and constant fluctuations around 75%. At this point, our Systems Eng team is refusing to deploy NCPA to linux boxes until it's fixed.

**Comment by jhomann** [comment]
So can I get some information on this? Is this an issue for people still? The CPU check right now is currently using a 1 second check time ... waits one second, does the math from the 2 points it grabs the CPU usage and basically averages it. This is done in psutil and not by us. Besides this, another useful way to watch CPU usage is using the `aggregate=avg` which will give the average cpu usage for ALL the cores. Which is probably a better metric to monitor with anyway.

Anyway, I'd like to close this since I don't think there is any more we can do with this.

**Comment by JAACNTT** [comment]
@scot0357 did you solved the problem of CPU Usage in NCPA?? Regards.
