### ISSUE TITLE
Linux partition size check percentage used not taking super user into account

### ISSUE THREAD

**Issue by krobertson71** [NagiosEnterprises/ncpa#102]
We were noticing that NCPA was reporting 47.7% used on /var but the system said we had 51% used on /var.

Unix admin looked at it and said that the agent was not taking into account the superuser blocks that only root can write to.

We can fix this ourselves by just adjusting the thresholds with that in mind.  But I was wondering if this is something we can set up in ncpa to add 5% to the reported used %.

**Comment by AMG1978** [comment]
Has there been any development on this?  I see scot0357 said it will be in v1.9.0 in January, but that was over 10 months ago.  I could really use this fix in my organization.

**Comment by jhomann** [comment]
I'm not sure if there is a way to check this or not. I can look into it but no guarantees I will be able to get it into 2.0.0

**Comment by AMG1978** [comment]
Please give it a go.  Having an alert for 93% and having to think in my mind "yeah that's probably close to full" is far from ideal.  Thanks for your support on this.

**Comment by giampaolo** [comment]
I'm not sure what component you guys rely on in order to get disk % usage (I'm not a Nagios user) but if you get it from psutil the reason why it's 5% short is because psutil doesn't take reserved blocks into account. Here is a summary of my findings: https://github.com/giampaolo/psutil/issues/829#issuecomment-223750462 
Feel free to contribute to that discussion if you want.

**Comment by jhomann** [comment]
Hi @giampaolo, thanks a lot for investigating.

For this particular agent -  which just a program that runs on a host and has an API that can return stats on the system - we use psutil for almost all of our monitoring metrics, which is why I've been creating issues! Hopefully we can find a good solution and I can better understand psutils.

**Comment by giampaolo** [comment]
OK, I fixed this in psutil: https://github.com/giampaolo/psutil/commit/3dea30d583b8c1275057edb1b3b720813b4d0f60.

**Comment by jhomann** [comment]
Great, thanks for the quick fix!

Not for myself:
- Need to add patch if we build with psutils < 4.3.0
- Check back in on this to verify its updated in next build of NCPA

**Comment by AMG1978** [comment]
Am I going crazy but is the 2.0.6 release for RHEL 5 x64 not containing this fix?  It should since 2.0.6 was long after this thread activity.

$ df -h /app
Filesystem            Size  Used Avail Use% Mounted on
/dev/fsname_masked
                      247G  203G   31G  **87%** /app

Yet ncpa shows:
$ /usr/local/nagios/libexec/check_ncpa.py -H servername_masked-t token -M disk/logical/\|app/used_percent -w 90 -c 95
OK: used_percent was **82%** | 'used_percent_0'=82%;90;95;

$ uname -a
Linux servername_masked 2.6.18-238.19.1.el5 #1 SMP Sun Jul 10 08:43:41 EDT 2011 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 5.6 (Tikanga)

$ rpm -qa | grep ncpa
ncpa-2.0.6-1.el5.centos.x86_64

*** Yes it shows centos there, but it was installed from "ncpa-2.0.6.el5.x86_64.rpm" , absolutely positively.

**Comment by jomann09** [comment]
Yeah that fix should definitely be in this unless there was a reason for psutils not to get updated... which I am pretty sure it was. I don't have any more el5 build machines because they stopped updating because of the repos shutting off. The only thing I can think of is psutils not being updated.

**Comment by AMG1978** [comment]
Correction, I dont believe it is an issue.
I decided to try 2.0.5 .4 .3 .2 .1 .0 and none worked.  I was puzzled.
I checked ps and I had this residing out there on this box
root     29081     1  0  2015 ?        05:37:46 ./ncpa_posix_listener --start

DOH!
2015!
So I killed it and restarted and turns out the 2.0.6 works perfectly on RHEL 5.
Thank you.

**Comment by jomann09** [comment]
Awesome I am glad you got it working!
