### ISSUE TITLE
NCPA build for Solaris 10 (SPARC and Intel)

### ISSUE THREAD

**Issue by SuperGoodMike** [NagiosEnterprises/ncpa#105]
Any chance you can release a NCPA package for Solaris 10?

**Comment by mpp4manu** [comment]
I am currently attempting to build the 1.8.1 agent (and attendant Python 2.7.8) on a Solaris 10 32-Bit server.  

So far, my efforts to compile Python using GCC have resulted in at best, only partial builds, but creation of the shared object file seems to consistently fail.  However, the Python executable does build and appears to be viable.  Getting to this point took a lot of work (setting PATH so that GNU build tools were used versus native Solaris tools) and manual tweaking of the Makefile.  I tried using the Python executable created to perform the other build tasks, but pip is missing and I know too little about Python to understand what is wrong (why couldn't this have been built in Java or Perl?).

Here's the last gcc commands and the resulting failure message:
gcc -shared  -Wl,-hlibpython2.7.so.1.0 -o libpython2.7.so.1.0 Modules/getbuildinfo.o Parser/acceler.o Parser/grammar1.o Parser/listnode.o Parser/node.o Parser/parser.o Parser/parsetok.o Parser/bitset.o Parser/metagrammar.o Parser/firstsets.o Parser/grammar.o Parser/pgen.o Parser/myreadline.o Parser/tokenizer.o Objects/abstract.o                                    Objects/boolobject.o Objects/bufferobject.o Objects/bytes_methods.o Objects/bytearrayobject.o Objects/capsule.o Objects/cellobject.o Objects/classobject.o Objects/cobject.o Objects/codeobject.o Objects/complexobject.o Objects/descrobject.o Objects/enumobject.o Objects/exceptions.o Objects/genobject.o Objects/fileobject.o Objects/floato                                   bject.o Objects/frameobject.o Objects/funcobject.o Objects/intobject.o Objects/iterobject.o Objects/listobject.o Objects/longobject.o Objects/dictobject.o Objects/memoryobject.o Objects/methodobject.o Objects/moduleobject.o Objects/object.o Objects/obmalloc.o Objects/rangeobject.o Objects/setobject.o Objects/sliceobject.o Objects/string                                   object.o Objects/structseq.o Objects/tupleobject.o Objects/typeobject.o Objects/weakrefobject.o Objects/unicodeobject.o Objects/unicodectype.o Python/_warnings.o Python/Python-ast.o Python/asdl.o Python/ast.o Python/bltinmodule.o Python/ceval.o Python/compile.o Python/codecs.o Python/errors.o Python/frozen.o Python/frozenmain.o Python/f                                   uture.o Python/getargs.o Python/getcompiler.o Python/getcopyright.o Python/getplatform.o Python/getversion.o Python/graminit.o Python/import.o Python/importdl.o Python/marshal.o Python/modsupport.o Python/mystrtoul.o Python/mysnprintf.o Python/peephole.o Python/pyarena.o Python/pyctype.o Python/pyfpe.o Python/pymath.o Python/pystate.o P                                   ython/pythonrun.o Python/random.o Python/structmember.o Python/symtable.o Python/sysmodule.o Python/traceback.o Python/getopt.o Python/pystrcmp.o Python/pystrtod.o Python/dtoa.o Python/formatter_unicode.o Python/formatter_string.o Python/dynload_shlib.o   Python/thread.o Modules/config.o Modules/getpath.o Modules/main.o Modules/gcmodule                                   .o  Modules/threadmodule.o  Modules/signalmodule.o  Modules/posixmodule.o  Modules/errnomodule.o  Modules/pwdmodule.o  Modules/_sre.o  Modules/_codecsmodule.o  Modules/_weakref.o  Modules/zipimport.o  Modules/symtablemodule.o  Modules/xxsubtype.o   -lsocket -lnsl -lrt -ldl   -lm ; \
        ln -f libpython2.7.so.1.0 libpython2.7.so; \

ld: fatal: file P,/usr/ccs/lib:/usr/lib: open failed: No such file or directory
collect2: ld returned 1 exit status
ln: cannot access libpython2.7.so.1.0
make: *** [libpython2.7.so] Error 2

It's just not building the libpython shared object, although I think at one point in past attempts, it did build it or something that looked like it, but I removed that because it came from a build with a large number of errors.  At a minimum, you need to add "/usr/sfw/include" to the includedir directive because that's where many of the required header files (Tcl/Tk, OpenSSL, etc.) can be found.

I then decided to load Sun Studio 12 on the box and try building it with a "native" compiler and build tools.  After setting environment variables, I forced the configure to use "cc" rather than "gcc".  Configure completes without error.  Executing make produces many warnings, but completes with a 0 exit status.  However, the following summary message at the end concerning the _ssl module is of concern:

Python build finished, but the necessary bits to build these modules were not found:
_bsddb             _sqlite3           _ssl

It does not say that it did not build the _ssl module and I'm not sure what this message means exactly.  The resulting python executable and shared object show no missing libraries.

Next I moved on to "make altinstall".  This completed in a manner similar to "make", but it also indicated that it could not find the Tcl/Tk headers despite the fact that their directories were explicitly listed in the configure command.  However, it did produce a viable python2.7 executable with no missing libraries.
PIP won't install as indicated in the original Makefile, so I had to install easy_install and then install it that way.  easy_install also allowed me to install many of the required Python modules, but pyOpenSSL and gevent failed, so I'm trying work around that.

I'll report back if I'm ever successful.

**Comment by jhomann** [comment]
Just an update. We now use python 2.7.11 along with the latest versions of all the libraries for python. When building the python binaries there is a way include the shared libraries if you do ./configure --enable-shared

**Comment by jomann09** [comment]
So I did a bit of a learning session and this is how I got it built/installed.

```
Installing on Solaris 10/11:

pkgadd -d http://get.opencsw.org/now

Select "all" when asked and read them in, then add the following to your env:

PATH=/usr/bin:/usr/sbin:/opt/csw/bin:/opt/csq/sbin:/usr/ccs/bin
export PATH

PKG_CONFIG_PATH=/opt/csw/lib/pkgconfig
export PKG_CONFIG_PATH

pkgutil -U

git
nano
wget
openssl_utils
libssl1
libssl_dev
libz1
libz_dev
python27
python27_dev
libffi6
libffi_dev
libsqlite3_0
libsqlite3_dev
gcc5core
gmake

We need to get into bash and move to main directory:

bash
cd ~

wget https://bootstrap.pypa.io/get-pip.py

git clone https://github.com/NagiosEnterprises/ncpa

Move into ~ ncpa/build/resources and run:
(MUST BE IN HOME DIRECTORY)

python2.7 -m pip install -r require.txt
python2.7 -m pip install appdirs packaging

useradd nagios
groupadd nagios

cd ncpa

chown -R nagios:nagios *

You can now build the actual python (make sure you're in the NCPA directory):

find /home/nagios/ncpa -name *.pyc -delete
mkdir -p /home/nagios/ncpa/agent/plugins
mkdir -p /home/nagios/ncpa/agent/var
mkdir -p /home/nagios/ncpa/agent/build
echo -n '' > /home/nagios/ncpa/agent/var/log/ncpa_passive.log
echo -n '' > /home/nagios/ncpa/agent/var/log/ncpa_listener.log
cd /home/nagios/ncpa/agent && python2.7 setup_posix.py build_exe

You will then have the entire agent built in:

/home/nagios/ncpa/agent/build/NCPA
```
You will have to create your own service for now and your own way of packaging... I will look into other ways of doing this and hopefully come up with a solution at some point.

The whole package should work just fine as is however you should know that certain things (such as the service module) will not work yet until NCPA has been updated to make that module work on Solaris.

**Comment by jomann09** [comment]
Closing this though as something we may look into doing in the future but we won't do it right now. If there is someone who wants to package it please do make a push with any necessary files for Solaris packaging.

**Comment by Kuma569** [comment]
I know this had been closed almost 2 years ago, but I'm having a trouble to install NCPA 2.1.6 on Solaris 10, due to NCPA is looking for OpenCSW repository, which our Solaris 10 is not using it. So I'm wondering if it's able to compile Nagios NCPA for Solaris 10 with using the actual Solaris Operating System libraries as opposed to OpenCSW? 

Sorry, I'm new to NCPA, so, I'm not so sure even this is appropriate place to ask this kind of question.  But here is the comment from Solaris admin ;

"It is apparent from various installation attempts of NCPA that OpenCSW is in use, since errors from the binary file as well as build-from-source attempts have outlined /opt/csw as a missing requirement in almost every error message.

At the very least, it would be nice to find out from the Nagios people what prerequisites are actually required for a Solaris 10 installation." 

Any advise?

p.s. On Solaris 11, it's been installed without any trouble.

**Comment by mpp4manu** [comment]
If you install the Solaris 10 development tools, you can build it using native Solaris libraries.

To be honest, I don’t remember the exact steps we took, however, it required modification of the code itself, which I believe we uploaded.  I no longer have a binary of the Solaris NCPA agent because we are 100% Linux now.

Michael

**Comment by Kuma569** [comment]
Thank you for the reply Michael, 

We still have a bunch of Solaris 10 servers so we need to figure out how to...   I will see if Solaris admins can use Solaris 10 development tools building NCPA.  

I'm looking for information regarding to this issue here and Nagios Support Forum, but, so far got not so much. If you could point out any useful links or information, that would be very appreciated.  

-Tatsuya

**Comment by mpp4manu** [comment]
It has been a long time since I dealt with this, but I seem to remember it being really difficult to get Python configured properly on the servers, mainly because we needed a version that was not directly supported by Solaris 10.

I believe we used the Solaris Studio suite to get the compiler needed to do the build, and I think we might have used it to build a version of Python we needed.  Because the servers on which this was done no longer exist, it may be hard to get any details.

I know we had to submit a fork for a Python library because it wouldn’t work with Solaris properly.

Your challenge here may be getting a more recent version of Python loaded on your servers.

If it were my choice, I’d use the NRPE agent on Solaris.  While I like some of the features of the NCPA agent, I’m not sure it’s worth the hassle as both function in similar ways.  I don’t work with Nagios much anymore, so maybe things have changed.

Michael

**Comment by jomann09** [comment]
Can you give me the error that it is giving when you're trying to run/install on your system? I would agree with the above that it might be easier using NRPE if you have to build from source because NCPA does require a lot of dependencies/libraries and you'd likely have to build python from source and probably more than one python module too.

**Comment by mpp4manu** [comment]
That is exactly my concern also.  That is what took us so long, along with the fact that a core Python library needed to “fixed” by us.  I think that fix was pushed upstream, so I hope it wouldn’t be an issue.

Michael

**Comment by Kuma569** [comment]
Thank you Michael, Jake,

I was thinking the same way, so looking at NRPE, too.  

However, because of NCPA's functionalities and security reasons (someone told me NRPE has some more security holes, bugs, etc than NCPA... ), also the other OS type servers will use NCPA across the board in our environment,  we prefer to use NCPA despite of the dis-advantages of building up a new one. 

These are the errors when they install NCPA on Solaris 10 server.  They are getting this error – even after creating a symlink to libgcc_s.so.1 :
  
[ Apr  3 10:43:37 Executing start method ("/usr/local/ncpa/ncpa_listener") ]
Traceback (most recent call last):
  File "/opt/csw/lib/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-solaris-2.10-sun4v.32bit.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_listener.py", line 3, in <module>
  File "/opt/csw/lib/python2.7/logging/__init__.py", line 26, in <module>
  File "/opt/csw/lib/python2.7/collections.py", line 9, in <module>
ImportError: ld.so.1: ncpa_listener: fatal: relocation error: file /usr/local/ncpa/operator.so: symbol _PyUnicodeUCS4_AsDefaultEncodedString: referenced symbol not found
[ Apr  3 10:43:37 Method "start" exited with status 1 ]
[10:43:45 ncpa.cfg.d]# ldd  /usr/local/ncpa/operator.so
        libpython2.7.so.1.0 =>   /usr/lib/libpython2.7.so.1.0
        libgcc_s.so.1 =>         /lib/libgcc_s.so.1
        libc.so.1 =>     /lib/libc.so.1
        libresolv.so.2 =>        /lib/libresolv.so.2
        libsocket.so.1 =>        /lib/libsocket.so.1
        libnsl.so.1 =>   /lib/libnsl.so.1
        librt.so.1 =>    /lib/librt.so.1
        libdl.so.1 =>    /lib/libdl.so.1
        libm.so.2 =>     /lib/libm.so.2
        libmp.so.2 =>    /lib/libmp.so.2
        libmd.so.1 =>    /lib/libmd.so.1
        libscf.so.1 =>   /lib/libscf.so.1
        libaio.so.1 =>   /lib/libaio.so.1
        libdoor.so.1 =>  /lib/libdoor.so.1
        libuutil.so.1 =>         /lib/libuutil.so.1
        libgen.so.1 =>   /lib/libgen.so.1
        /platform/sun4v/lib/libc_psr.so.1
        /lib/libm/libm_hwcap1.so.2
        /platform/sun4v/lib/libmd_psr.so.1
[10:43:51 ncpa.cfg.d]#

**Comment by jomann09** [comment]
Just to see if this is the issue, can you try running it along with setting the library path? Like:
`LD_LIBRARY_PATH=/usr/local/ncpa /usr/local/ncpa/ncpa_listener -n` and see if it can load it?

**Comment by mpp4manu** [comment]
You have given the some of the reasons why I went through this effort.  Mainly, I wanted to use a single agent.

I think you’re going to need to get a new version of Python on the server first.  If you have access to a Solaris package, that would be better, though you won’t get it from Oracle.  SunFreeware might have it.  I’d focus on that first.

Second, I don’t think you can use the gcc compiler here, though I may be misinterpreting the output here.  You must use a Sun native compiler.

If you’re not successful, you try to push your alerts to the NRDS interface using a cron job running the monitors.

Michael

**Comment by Kuma569** [comment]
Thank you, Jake, Michael,

Looks like Solaris Admins can now start NCPA on their Solaris 10 server setting up the PATH as Jake mentioned. Here is the comment from them:

--
Fixed.  We need the developer to file a bug and add LD_LIBRARY_PATH=/usr/local/ncpa to the service they are installing like this

svccfg –s ncpa_listener
svc:/site/ncpa_listener> setenv LD_LIBRARY_PATH /usr/local/ncpa
svc:/site/ncpa_listener> exit
svcadm refresh ncpa_listener           #reload the config with new env value
svcadm clear ncpa_listener                  #get out of maintenance state

svc:/site/ncpa_listener> listprop
multi_user_dependency             dependency
multi_user_dependency/entities    fmri     svc:/milestone/multi-user
multi_user_dependency/grouping    astring  require_all
multi_user_dependency/restart_on  astring  none
multi_user_dependency/type        astring  service
start                             method
start/timeout_seconds             count    60
start/type                        astring  method
start/exec                        astring  "/usr/local/ncpa/ncpa_listener"
**start/environment                 astring  LD_LIBRARY_PATH=/usr/local/ncpa**
stop                              method
stop/exec                         astring  "kill $(cat /usr/local/ncpa/var/run/ncpa_listener.pid)"
stop/timeout_seconds              count    60
stop/type                         astring  method
refresh                           method
refresh/exec                      astring  :true
refresh/timeout_seconds           count    60
refresh/type                      astring  method
startd                            framework
startd/duration                   astring  transient
tm_common_name                    template
tm_common_name/C                  ustring  ncpa_listener
tm_description                    template
tm_description/C                  ustring  "The ncpa listener service. Allows connections to ncpa API."

--
May be I should open a new thread to add that LD_LIBRARY_PATH=/usr/local/ncpa?

**Comment by jomann09** [comment]
Yeah we should move this into a new github issue. It seems that certain systems aren't able to find the libraries that are packaged with NCPA. I found SLES 11 also has this issue and I know there was an older Debian and an older OpenSUSE with it also.

**Comment by Kuma569** [comment]
Thank you Jake,  I will then move this topic to a new GitHUB issue.

Thanks a lot!
