### ISSUE TITLE
Feature request: Support ZFS filesystem checks natively

### ISSUE THREAD

**Issue by pittagurneyi** [NagiosEnterprises/ncpa#1076]
On nearly all my systems ZFS is used as main filesystem.

Currently only that which is accessible via psutil, i.e. mount points, is available via NCPA.

What I would like to see is native support for:

ZFS Pool health state (extracted from `zpool status`)
- current state: i.e. ONLINE, FAULTED, etc.
- last scrub: if too long ago, mark as warning/error
- known data errors

ZFS Pool available space (extracted from `zfs list -o space`)

Sometimes, for example on backup systems, the ZFS datasets actually containing the data aren't mounted - on purpose due to how zfs send/recv works -, meaning there is no way to get the free space via psutil. It just shows 0% for the pool mount point, although it might be 80% filled.

**Comment by ericloyd** [comment]
There is a ZFS plugin at https://exchange.nagios.org/directory/Plugins/Uncategorized/Operating-Systems/Solaris/check_zfs/details that you might be interested in.  The use cases for ZFS monitoring being built in to NCPA are limited, so I imagine it will be faster to deploy that plugin than to wait for NCPA to be updated to include that functionality.

**Comment by ericloyd** [comment]
While I agree with you, the overall penetration rate of ZFS is quite small.  So including it as part of the stock NCPA install means adding it to a large portion of installs where it won't actually be used.  That aside, the problem is more that the way NCPA works is that it does every check, every time, using tools available to Python.  If what you want is the output of zfs list -o space, then why not just write a quick plugin yourself that does that:

One-liner:

#!/bin/bash
zfs list -o space "$1" tail -1 | awk '{printf ("%s: Used: %s, Free: %s\n", $1, $2, $3)}'


Usage:

<script> /mnt/tank/filesystem

**Comment by MrPippin66** [comment]
I would echo Eric's statement. However, even so, for NCPA to support that tech, it's really dependent on the upstream modules NCPA uses to obtain that information. AKA, if "psutil" adopted it, having it reported in NCPA would be a much simpler solution.

So...I would recommend putting that request into the "psutil" maintainers project, but as Eric has already stated, the overall adoption of ZFS isn't widely used as far as the overall landscape NCPA and "psutil" covers.

**Comment by ericloyd** [comment]
Great idea - go bug the Python people to add support!  :-)
