### ISSUE TITLE
Allow Configuration to be modified from the browser

### ISSUE THREAD

**Issue by ne-bbahn** [NagiosEnterprises/ncpa#1144]
The current Admin pages show the various configuration options and the message:

> This section is currently in read only mode and any setting changes will not be saved. This will be updated in future versions.

This issue is to implement editing of those setting from those pages.

**Comment by ericloyd** [comment]
Ugh.  I have such misgivings about this.  I never want the settings to be configurable from the web interface because the thought of having another attack surface makes me cringe.  The API key (or whatever it's called, since it's not consistent) allows read-only access to the API stack and to execute arbitrary code as it is already (the plugins).  Proper management of the configuration file via existing file management is much preferred over poking things with a web browser (for me, at least).  Plus, it's one less thing that you have to worry about code injection if someone gets your key.

Still, I get that lots of people wants what they wants, and some of them wants web-based configs.  I'll watch from the sidelines and try not to comment too much. :-)

**Comment by omnitec** [comment]
On Wed, 3 Apr 2024, Eric Loyd wrote:

> Ugh.  I have such misgivings about this.  I never want the settings to be configurable from the web interface because the thought of having another attack surface makes me cringe.  The API key (or whatever it's called, since it's not consistent) allows read-only access to the API stack and to execute arbitrary code as it is already (the plugins).  Proper management of the configuration file via existing file management is much preferred over poking things with a web browser (for me, at least).  Plus, it's one less thing that you have to worry about code injection if someone gets your key.
>
Totaly agreed. Good security practices are to NOT allow an attack vector
that is not really needed.

**Comment by ne-bbahn** [comment]
The idea was to allow modification of settings such as enabling/disabling logging, setting `Log Level`, setting up passive through NRDP/Kafkaproducer and setting plugin timeout. The intention was to leave potentially higher-risk settings such as file targeting, user/group settings, SSL version and plugin directives in read-only to minimize the surface area.

**Comment by ericloyd** [comment]
I don't get "why" though?  If you still have to manage a config file to do things like set community_string and where the plugins directory is and what XI server to send NRDP data to, then what's the point in splitting it up so that some of those things are configurable from a web interface and some are not?  What happens when new features are added?  Does the parser need to be updated with a whitelist/blacklist of things that are allowed/disallowed via the web page?  Are you going to sanitize the data for "timeout" so that "300" doesn't become "300\ncommunity_string=mybackdoor"?

I just think that one less thing to worry about from a sysadmin perspective is better.  Please, if you're going to add web-based configuration to NCPA, then make it OFF by default.
