### ISSUE TITLE
Can't get process count from ncpa 1.7.2

### ISSUE THREAD

**Issue by prakhead** [NagiosEnterprises/ncpa#135]
Hi, I am struggling to get a process count to work as a check, I am not sure if I am doing something wrong or it is a problem with NCPA itself.
I have tried many different way to get this to work, where is an example:

`https://myserver:5693/api/process/running/myprocess/?token=mytoken&check=1`

Returns
`{
  "value": {
    "returncode": 0,
    "stdout": "OK: Process count for processes named myprocess was 1c | 'process_count_0'=1c;;;"
  }
}`

and 

`https://myserver:5693/api/process/running/notmyprocess/?token=mytoken&check=1`

`{
  "value": {
    "returncode": 0,
    "stdout": "OK: Process count for processes named notmyprocess was 0c | 'process_count_0'=0c;;;"
  }
}`

Both outputs are OK status to nagios but I would like critical when myprocess isn't  running.

Can anyone point me in the right direction please?

**Comment by krobertson71** [comment]
it's because by default the check takes a MORE THAN approach.  So 0 just comes back good and so does the other one.  Weird I know.

If you put this into a nagios check (I haven't testing this with the url) you can do 

/check_ncpa -H Hostname -t 'mytoken' -P 5693 -M 'process/theprocess/count' -c1:

This will check to see if a single process is running, if it's not, or running more than 1 it will return a critical.

If you want to say tell if more than 10 but less than 20 you could do:

/check_ncpa.py -h Hostname -t 'mytoken' -P 5693 -M 'process/savefs/count' -w10: -c20

Here is the link to the page that explains how you can set these to fit your situation.

https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

You want to look at TABLE 4
