### ISSUE TITLE
Nagios core 4.0.8 Plugin "check_disk" doesn't work with NCPA check_ncpa.py 0.3.1

### ISSUE THREAD

**Issue by swaroopv2** [NagiosEnterprises/ncpa#149]
Nagios core 4.0.8 Plugin "check_disk" doesn't work with NCPA check_ncpa.py 0.3.1. I dropped the "check_disk" plugin into /usr/local/ncpa/plugins/ directory and restartede NCPA listener on Remote Host that is being monitored. When I went to http://remotehostname:5693/api/agent/plugin I noticed that the check_disk plugin is present in the output which tells me that the NCPA agent accepted it as the plugin. From Nagios Core Server when i issue the command like below I am getting errors.

[root@NagiosCore ~]# /usr/local/nagios/libexec/check_ncpa.py -H RemoteHostName.domain.net -t nagiostoken -M 'agent/plugins/check_disk' -a '-w 20% -c 10% -p /'
Unable to run check on non-child node. Revise your query.

**Comment by jm-welch** [comment]
I ran into the same problem, and it appears to be due to the presence of the `/` in the path you want to check - since check_ncpa.py converts the arguments to a URL, it's essentially becoming: `http://RemoteHostName.domain.net/api/agent/plugins/check_disk/-w/20%/-c/10%/-p//&token=nagiostoken', which won't work.

If you're just looking to monitor a single disk per check, it may be easier to use the builtin disk metrics via `check_ncpa.py -H RemoteHostName.domain.net -t nagiostoken -M 'disk/logical/_/free' -w 20 -c 10` (or something similar to that - I'm on my home machine, so I don't have NCPA to test with at the moment).

If you're using the Nagios Core check_disk to check multiple disks at once (which is where I was), I wasn't able to find a way to make NCPA do that. I ended up writing a small script that I put in the plugins directory to do it for me.

```shell
#! /bin/bash
./check_disk -w 20% -c 10% -p / -p /tmp -p /var -p /var/log -p /opt -w 30% -c 15% -p /bkup
```

(again, an approximation, as I'm going from memory here)

Then I call that from Nagios via:

`check_ncpa.py -H $HOSTNAME -t $TOKEN -M agent/plugin/check_all_disks`

**Comment by jhomann** [comment]
I'm going to close this as resolved since @jm-welch's response is correct. Since the API uses / you cannot use / as variables for the plugin which is why NCPA uses | instead of / for C:| and whatnot. The above answer is unfortunately the best solution to the problem without rewriting parts of the system to convert | -> / or something along those lines.
