### ISSUE TITLE
"units" and "unit" issue

### ISSUE THREAD

**Issue by wangyishuai007** [NagiosEnterprises/ncpa#207]
NCPA Documentation
> The API
...
unit
This will be what the unit of the item should be. So if there is something you would rather see as bytes rather than B, specify unit=bytes instead of B. This is not recommended, but in the case that NCPA guesses the wrong unit, it can be rectified using this.
units
This is the prefix that will be appended to the unit. You can specify K, M, G or T for kilo, mega, giga or tera in regards to units. This will modify the size of the number returns and tack the appropriate prefix onto the unit. Note this will not affect items whose unit is %.
...

check_ncpa.py --help
>
...
  -u UNIT, --unit=UNIT  The unit prefix (M, G, T)
  -n UNITS, --units=UNITS
                        What should be used in place of the default unit. As
                        in, instead of 'b' as a unit, it will use this.
...

Why is the opposite?
Later, modify?

**Comment by jhomann** [comment]
I believe the UNIT is to overwrite the unit that NCPA will give the check - while UNITS is to specify what the measurement should be. Example: if you are getting the bytes from an interface if you do not define the UNITS it will come back as bytes, if you set the units to M then it'd give you Mb but not actually change the unit b.

This could maybe be changed to not be so confusing but it would have to wait until an NCPA 2.0 so that we could change it after deprecating it so it doesn't break anyone's configurations.

**Comment by jhomann** [comment]
I've updated these and will be changed to make more sense in the 0.4.0 version of the check_ncpa.py
