### ISSUE TITLE
NCPA LaunchDaemons Delay Option

### ISSUE THREAD

**Issue by loopway** [NagiosEnterprises/ncpa#214]
NCPA is started with help of the LaunchDaemon on Mac OS X. I specifically monitor only selected file systems with nagios. After a reboot of the macosx server, I see the following error on the nagios server: "Unable to run check on non-child node. Revise your query." It seems that at the time the NCPA is started by the LaunchDaemon the filesystems (volumes) are not yet mounted. I could not find any documented LaunchDaemon option to wait for the file system mounts or even just delay the start for a few seconds. A quick and efficient solution might be to implement a new flag to the two NCPA daemons to delay the start of their services by a supplied time (seconds). A shell wrapper script would be fine too in my opinion.

**Comment by jhomann** [comment]
I think I know of a way to add this. I will definitely add an option in the ncpa.cfg that will allow you to set the delay something along the lines of `start_delay = 30` where the number is in seconds. This option could work on any system. Essentially you'd probably only want this for passive checks but I will add it in for the active checks (the Listener) also since it should be fairly simple.

**Comment by jhomann** [comment]
This has been added in 07e195d023845a23a94cc0d0217ec31d8e9f283a
