### ISSUE TITLE
Timeout for passive checks

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#226]
#223
At the moment, the timeout value defined in ncpa.cfg [plugin directives] section is regarding active and passive checks. Thats a little bit confusing. It would be great, if there is an extra timeout config directive in [passive] section. Then these maybe different values could be delivered to function: execute_plugin.

**Comment by jhomann** [comment]
[plugin directives] are just values that are specific to plugins, not necessarily active/passive checks. I did it that way because it's easier since you don't need to know if you're running it via the web API or via the internal API (which is how NCPA does passive checks) and essentially it's running a plugin whether you're polling it actively or passively.

Anyone else have thoughts on this?

**Comment by jhomann** [comment]
Closing this due to still pretty sure it should be in plugin directives section since it applies to both the listener and the passive check! We can revisit it sometime later if it becomes an issue. There is a stub in the current ncpa.cfg for people to use if they want to add a timeout.
