### ISSUE TITLE
Question regarding delta method

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#243]
Hi!

How does the delta method work? I suppose it is intended for network related checks only?
For testing purposes i have made a cpu-check with the delta method enabled. I  If the check will be executed via nagios and normal_check_interval 5m, the output is always 0 percent. If i call the check_ncpa.py in the cli, with maybe a interval of 10 seconds, the output ist not 0 percent. I am a little bit confused about that.

**Comment by ccztux** [comment]
Maybe it could be documented more verbose just as the aggregate method.

**Comment by jomann09** [comment]
The delta only does a short sample period. I'll look at it and get back to you, there is a way to extend it. Just remember that it has to stop and wait to collect data when it does the delta checks. It is mostly for anything that you need to get "per second" essentially. It's one of those parts that isn't well documented that I would like to document better soon.

**Comment by jomann09** [comment]
I'm adding this as a bug that I will be fixing in 2.

When you use the delta=1 method, the first call you make returns a 0 ... this is fine, technically, since your last call was never made - however, I think that one of two things should happen on the first call:

- On startup, NCPA records a value for each of the nodes that allow delta values... and upon receiving a delta value it should then check against that last known value and average it out over the time since the last call. The downside to this is that it would give you a very large average, which could be okay for the first call.
- On the call for delta=1, if there is no value ... the function should sleep for 1-5 seconds and get the latest data to delta ... then return and store that value. This ensures that if there is data, it'll get the most recent data. If there is data then it'll use that data and time as the last know data and function as normal. I am currently leaning towards this way of doing it since it should be faster to implement and not require so much overhead.

As a side note - we are currently using the `pickle` module to store the output of values that we use the delta method on. Since we now have a SQLite db - I think it might be useful to start using the database as a way to store these instead of the file system, but I will probably save that for a different version of NCPA.

**Comment by jomann09** [comment]
Not a pretty fix but upon knowing the pickle file is not there, it'll return false, and then will re-run the method to get check data and re-do the delta value check against the pickle file. 7b7ab126839d900ddf8cefaad8be9f26a9306e8d
