### ISSUE TITLE
No Input Checking of Logical DIsk Units

### ISSUE THREAD

**Issue by antonc42** [NagiosEnterprises/ncpa#251]
When the units option is used with a logical disk, it appears that any single character is recognized as valid input. Only the characters `K,k,M,m,G,g` actually change the value from the default bytes. However, the invalid character is still shown followed by `b` in the units.

Valid character (`/api/disk/logical/|?token=token&units=m`):
```json
      "total_size": [
        [
          30335.164416
        ], 
        "Mb"
      ], 
      "used": [
        [
          1213.620224
        ], 
        "Mb"
      ], 
      "free": [
        [
          29121.544192
        ], 
        "Mb"
      ], 
```

Invalid character (`/api/disk/logical/|?token=token&units=^`):
```json
      "total_size": [
        [
          30335164416.0
        ], 
        "^b"
      ], 
      "used": [
        [
          1213620224.0
        ], 
        "^b"
      ], 
      "free": [
        [
          29121544192.0
        ], 
        "^b"
      ], 
```

OS: CentOS 7 x86_64
NCPA: v1.8.1 via the `ncpa-1.8.1-1.el7.centos.x86_64.rpm` package

**Comment by jomann09** [comment]
Just an update on this I believe this is also fixed in 2.0.0-alpha already but will definitely do a test on this so it's recorded that it has been fixed. The `units` should only work if the unit is `b` or `B` and then if you want to override your unit name you use `unit` ... this caused a lot of confusion before and will be better documented in the future.

**Comment by antonc42** [comment]
Thanks!

**Comment by jomann09** [comment]
Alright, tested this in my 2.0.0-alpha versions and it is definitely not allowing you to arbitrarily add whatever kind of unit to the bytes that you would like. This is probably due to the fact that I am now checking to 1) make sure the data is in bytes before trying to convert, and 2) verifying the value is inside the list of proper values that can be used.

As a side note, in 2.0.0 there are going to be a few extras, so now you can use all of these:
`k, Ki, M, Mi, G, Gi, T, Ti`
