### ISSUE TITLE
Add development branch

### ISSUE THREAD

**Issue by jm-welch** [NagiosEnterprises/ncpa#253]
A development branch separate from `master` should be created. That way, `master` can always reflect the current 'release' code, while the `develop` branch is the staging ground for changes submitted by contributors. Tagging helps keep versions straight, but `master` should always be fully-vetted, functional code - if there isn't a branch for a contributor to submit to other than master, it breaks that relationship.

Honestly, I'm a huge fan of [Git Flow](http://nvie.com/posts/a-successful-git-branching-model/) as a branching model, but it may be seen as overkill for a project of this size.

**Comment by jomann09** [comment]
Yeah, I definitely agree! It was always the intention to make 2 branches, and have `master` be the stable ready-to-use code. It was all merged together though for 2.0.0 (one reason being I am the only dev now) due to not having a defined model and there being multiple branches with random things in them. I would like to use the model in the article you've given, even if it's a smaller project - having a layout for branching is a good idea.

I will take a look at the article, from a brief glance it seems a lot like the branching model I had in mind, but following that will make it easier for new people to understand.

**Comment by jomann09** [comment]
I will update this tonight, since it does make it a bit easier to do pull requests.

**Comment by jomann09** [comment]
Added a `dev` branch :) I shortened the name because I just like it short as possible for typing in ... I think we will stick fairly close to what the Git Flow article was talking about in terms of branching off for bug fixes, releases, and any really major changes.
