### ISSUE TITLE
2.0 Windows build

### ISSUE THREAD

**Issue by oneoffdallas** [NagiosEnterprises/ncpa#257]
The 2.0.0.a.exe does not create a listener service during install on a Windows system. I tested it on two different Windows builds -- Server 2012 R2 and Windows 10 Pro. Thanks!

**Comment by jomann09** [comment]
I'm sorry about that! I actually hadn't built a new one since my build server had some mismatched packages. I've uploaded the correct one - give it at least 5 minutes before trying to download it after I send this. I was working on nightly builds and they aren't all being built automatically yet so I still have to copy them over manually.
