### ISSUE TITLE
Request build for AIX 7.1 / 6.1

### ISSUE THREAD

**Issue by daniel-ledford** [NagiosEnterprises/ncpa#258]
We use nagios extensively at our company, and have been implementing NCPA as our go to agent of choice. However, we do have several AIX 6.1 and 7.1 servers that we would like to monitor using NCPA. I know there is no build currently out there for AIX but we would like to formally request this build.

**Comment by jomann09** [comment]
The problem we currently have with many of these systems (AIX on powerX, Solaris on SPARC, HP-UX, etc) is that we don't have the systems to build on. If you have any information on how we could go about making these builds I'd be happy to try and get them created officially otherwise you can also build them if you have access to one that you can install python and the required packages on.

**Comment by bgshacklett** [comment]
I've been looking into this a little bit, and it seems like there are some Power servers available on Ebay for a fairly reasonable price. I might be interested in putting something together at my house and making it publicly available. Would there be any hardware requirements for the build server? Specific processor features required for build optimization, for instance? also, does anyone know of any CI/CD solutions that exist or could be easily ported to AIX, or some of these other, less common, platforms?

Another thought is there are some "cloud" providers that offer AIX LPARs either on a per-day or monthly basis. Unfortunately, they're somewhat expensive ($20/day or ~$200/mo).

**Comment by jomann09** [comment]
Sorry I haven't responded yet! It's been a really busy week.

I had also thought about purchasing a few used version of a couple different systems on Ebay but I am not sure about how the licensing for the AIX and Solaris systems is handled. I woudn't want to have a system that can't get packages for installation because we need the latest versions for our builds to keep up with security updates etc.

We have in the past used the solution that you mentioned for the VM/LPAR version of AIX in particular for NRPE and other projects but it's extremely expensive for the time we would get and the build process for NCPA requires a lot of set up on most systems I am not sure we could make a working build very fast and would cost a lot to do each time we needed to make a new build.

**Comment by metabsd** [comment]
We can give you remote access for free to AIX System. Are you interessed ? One third of our server are AIX. We need that.

**Comment by jomann09** [comment]
Thanks for the offer! I see you sent us a ticket about this too, we can communicate through that and see what we can do. I'd like to get NCPA built for AIX.

**Comment by jomann09** [comment]
Currently testing an NCPA 2.0.3 RPM for AIX 7.1 (should work on AIX 7.x) but I am not sure if it'll work on 6, we may need to build one on an AIX 6 system for those who need it at some point.

**Comment by jomann09** [comment]
If anyone else wants to test this, there is a dev build in https://assets.nagios.com/downloads/ncpa/dev/ for AIX 7.1 +

**Comment by jomann09** [comment]
Closing this, 2.0.4 has a build now for AIX 6.1+ here https://www.nagios.org/ncpa/#downloads
