### ISSUE TITLE
[1.8.1] Process checks are using regex

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#270]
Hi!

Process checks are using regex like this:
```
^(.*)process_to_monitor(.*)$
```

This check is OK, process really exists:
```
[root@localhost libexec]# ./check_ncpa.py -H my_ip_address -t my_token -M /api/process/svchost.exe -w 1:15 -c 1:20
OK: Process count for processes named svchost.exe was 14c | 'process_count_0'=14c;1:15;1:20;

```

This check is NOK, because it returns OK state, allthough this process doesnt exists:
```
[root@localhost libexec]# ./check_ncpa.py -H my_ip_address -t my_token -M /api/process/sssssvchost.exeeee -w 1:15 -c 1:20
OK: Process count for processes named sssssvchost.exeeee was 14c | 'process_count_0'=14c;1:15;1:20;
```

I think, this should be changed.

**Comment by jomann09** [comment]
You are certainly correct! However, this is fixed in NCPA 2, with the processes endpoint changing to reflect that of the services endpoint. Both now use exact match by default and allow a `match` parameter to be passed to use regex or a plain search algorithm.

Here's the HTML page in the help section (since it hasn't been added to the NCPA site yet - since there isn't one even though we are really close to releasing 2)

![image](https://cloud.githubusercontent.com/assets/6423215/21054153/15920380-bdf2-11e6-9079-04a9cc4e1ccc.png)
