### ISSUE TITLE
Passing parameters to API plugin fails

### ISSUE THREAD

**Issue by celticguy42** [NagiosEnterprises/ncpa#287]
Command:

./check_ncpa.py -T 30 -H servername -t faketoken -M /agent/plugin/check_item.ps1/Param1

fails to pass the parameter "Param1" to the PowerShell script.  This worked fine with 1.8.1.

**Comment by jomann09** [comment]
That should be backwards compatible, are you using the latest version of the check_ncpa.py plugin?

Also, you should consider using `-M plugins/<plugin_name>` now due to the `agent/plugin` being deprecated. You can also pass your arguments via `-a`, which is the preferred method of passing arguments.

```
./check_ncpa.py -T 30 -H servername -t faketoken -M plugins/check_item.ps1 -a "Param1 Param2"
```

Each argument is separated by a single space. More info here.

**Comment by celticguy42** [comment]
Thank you!  We've updated the command with the new format.
