### ISSUE TITLE
Process check on windows NCPA ver 2.1

### ISSUE THREAD

**Issue by kingdingaling83** [NagiosEnterprises/ncpa#299]
hey there
i'm having trouble checking for a process on a windows server 

here's my check command
`/usr/local/nagios/libexec/check_ncpa.py -H 10.252.32.253 -t 'mytoken' -P 5693 -M 'process/farmerswife Server 6.0 Service Pack 4/count' -w 2 -c 1:`

here's an image of the process
[https://s23.postimg.org/xfv1u6juz/Screen_Shot_2017_01_12_at_15_32_40.png](url)

**Comment by kingdingaling83** [comment]
sorry you'll need to cut and paste the image link

**Comment by jomann09** [comment]
So the first thing that might be problem is the name of the service. Is that what it is named in the windows Services list? Typically the Name column is the name that NCPA will recognize for a service.

Example:
![image](https://cloud.githubusercontent.com/assets/6423215/21896234/42c0ef14-d8ab-11e6-9b21-9dea8d2567b4.png)

So if you are using the right name, the second thing you should be doing is:
```
./check_ncpa.py -H <hostname> -t 'token' -P 5693 -M 'processes' -q 'name=farmerswife,match=search' -w 2 -c 1
```
Would give you the count of all processes that have the search string `farmerswife` in them. So that would check also.

**Comment by kingdingaling83** [comment]
it's a process not a service from what i can see.

**Comment by jomann09** [comment]
You're right, sorry I was mixing the two, the way that I gave the check should work though

**Comment by kingdingaling83** [comment]
great i'll give it a go tomorrow

**Comment by jomann09** [comment]
Closing this due to being open for 10 days, if you have any more issues don't hesitate to post back or make a new issue!
