### ISSUE TITLE
Add Continuous Integration/Testing

### ISSUE THREAD

**Issue by scot0357** [NagiosEnterprises/ncpa#30]
Add tests for existing functionality so we can avoid breaking items in the future, or at least have a place to make sure once its unbroken, it stays unbroken.

**Comment by bgshacklett** [comment]
I've just enabled TravisCI on my fork and created a .travis.yml file in a feature branch. I'm not sure if it covers all of the requirements, but it gives a good boolean pass/fail on any branch which contains a .travis.yml file in addition to listing how many tests in the script output.

Example here: https://travis-ci.org/bgshacklett/ncpa/builds/91140392

**Comment by jhomann** [comment]
Once 2.0.0 is finished I am going to do two different CI integrations:
Travis CI (Linux and Mac OS X) and AppvVeyor (Windows)

Since the old versions of CI were pretty hacked together and multiple people were doing their own thing we are going to redo the tests and CI integration before we continue with feature requests after 2.0.0.

**Comment by jomann09** [comment]
Closing this for now, we have some basic integration with Travis CI and will need to work on some better tests but for the time being I am closing this as since pytest now works and we can start using it.
