### ISSUE TITLE
issues calling ./check_ncpa.py from ./check_ncpa.py

### ISSUE THREAD

**Issue by ashleydrees** [NagiosEnterprises/ncpa#303]
Nagios Core + Ubuntu and Windows clients. I have recently updated all clients to NCPA 2.0.1, i have a situation where i monitor several windows 2012 servers which are behind a firewall with NAT, I run NCPA on a Ubuntu server which is used to monitor the windows servers bouncing queries from the Ubuntu server to the windows machines, it has been working up to the upgrade to 2.0.1.  

I can check all/any metrics on the windows servers using the GUI when inside the NAT, 
I can directly check the windows servers from the monitoring server using the following type of syntax.

./check_ncpa.py --hostname=172.16.8.243 --token=something --metric='disk/logical/C:|'

etc etc...

When i try and check a machine from the Core server via the monitor server behind the NAT firewall the following happens.

though i can use the metric "disk" and --list which shows me...

 logical/
        O:|/
            used_percent: [93.6, u'%']
            used: [100360065024, u'B']
            total_size: [107237863424, u'B']
            free: [6877798400, u'B']
            fstype: NTFS
            device_name: [u'O:\\']
            opts: rw,fixed
        C:|/
            used_percent: [61.1, u'%']
            used: [65504210944, u'B']
            total_size: [107267223552, u'B']
            free: [41763012608, u'B']
            fstype: NTFS
            device_name: [u'C:\\']
            opts: rw,fixed

using 

./check_ncpa.py -H nat.domain.tld -t asecret -M 'plugins/check_ncpa.py' -a "--hostname=172.16.8.243 --token=asecret --metric='disk' --list"

if i actually try and check a disk...
./check_ncpa.py -H nat.domain.tld -t asecret -M 'plugins/check_ncpa.py' -a "--hostname=172.16.8.243 --token=asecret --metric='disk/logical/C:|'"

It tells me...
Unable to run check on node without check method. Requested 'disk' node.

i CAN run anything that does not have a foreward/slash in the metric.

./check_ncpa.py -H nat.domain.tld -t asecret -M 'plugins/check_ncpa.py' -a "--hostname=172.16.8.243 --token=asecret --metric='processes' --warning=100 --critical=200"

OK: Process count was 71 | 'process_count'=71;100;200;

Works fine from my CORE server, so what i am trying to do works, but anything with a forward slash does not.

I have tested out the format of each query on the monitor machine behind the nat.... is there something special i should be doing to craft the second step? 

I might try SSH for the first step in a while, a VPN is currently out of the question - and i am not about to start mapping multiple ports for all the internal devices i want to manage - this was working with the earlier (1.8.x) NCPA and its check_ncpa.py - if i am now trying to do something that is now disallowed, i'll quickly move on.

**Comment by jomann09** [comment]
I believe this is due to how the check_ncpa.py is converting the arguments before passing the values. Let me do a couple quick tests and see if that is the reason. The check_ncpa.py plugin was updated around the time NCPA 2 came out to use a different way of making requests that is faster and does not cause some disconnect issues people were getting.

**Comment by jomann09** [comment]
It's definitely because of the / in the command arguments ... really I have always had a problem passing them in the URL with a / like this because it's always going to break things... I think we will have to use a different notation to represent slashes unfortunately or check if they are inside quotes on the NCPA side. Either way this'll get fixed in version 2.0.2

**Comment by jomann09** [comment]
Fixed in b1a4ee9c60e156314a17b8ca1c7fd21f038f01d4

I suggest when 2.0.2 is released you upgrade your check_ncpa.py to the new 1.1.0 version also just to make sure it works properly. From my testing, the way you originally did it should work with the new versions.

**Comment by ashleydrees** [comment]
I already have the check_ncpa.py at version 1.1.0.

I noticed that adding --units G to the end of a working 'disk/logical/C:|' query brings.

Usage: check_ncpa.py [options]
check_ncpa.py: error: no such option: --units

Is there a time frame for the 2.0.2 release?

**Comment by jomann09** [comment]
Oh the newest versions of check_ncpa.py use `--unit=G` (also `-n`) or `--unitprefix=G` (also `-u`) and the difference is that the unit prefix actually converts the unit and there are only a set amount of prefixes available. This was a huge area of confusion for a lot of people previously. The unit value actually overrides the name of the unit and sets the unit to that. It does not do any conversion or anything like that.

The 2.0.2 release should be this week, I have a couple more things to fix and then I will build it and test it.

**Comment by ashleydrees** [comment]
Thanks, i'll keep a close eye for a release. 

Just to give a bit more info - i copied the "--units G" (actually the whole query string) directly from NCPA 2.0.2 running on windows when it gave me an example - is it giving me the wrong syntax?  I tried with "--units=G" and it works as i expect.

**Comment by jomann09** [comment]
Thanks for finding that, it is giving you the wrong syntax. Looks like I had it set to use "units" in the command line output example for that. I am changing this now for 2.0.2 also.

I would recommend using `-u G` since no matter what version of the check_ncpa.py script you use, it will always do the same thing and will always be available. The naming changes are only for the `--` version of that argument.

**Comment by ashleydrees** [comment]
I am also having issues with several check_* plugins which seem to need higher permissions - things like check_ide/smart which were working previously but now do not, if i run it from the command line as the nagios user it works but with the same thing using check_ncpa.py it fails.

For instance ./check_fail2ban which is in sudoers and also has a stanza in nrpa.cfg, it was working before but no matter how set it up - i cannot get it to run - gives the error .

```
COMMAND: /usr/local/nagios/libexec/check_ncpa.py -H server.domain.tld -t aSecret -M plugins/check_fail2ban -a "-w 10 -c 20"
OUTPUT: ERROR  Unable to contact server. Is it running?
CHECK FAIL2BAN ACTIVITYCRITICAL - non-zero exit code during testing fail2ban-client ping, check if the server is running and if you have the good permissions

```

from the shell as nagios.

sudo ./check_fail2ban -w 10 -c 20
CHECK FAIL2BAN ACTIVITY - OK - 6 detected jails with 0 current banned IP(s)

Is there some change i have to take into account with sudo commands in teh 2.x series of NCPA?

**Comment by jomann09** [comment]
Yeah that is due to the changing of the daemon running as root. So it will always be an issue. In NCPA 2, the `uid` and `gid` variables that are set in the `ncpa.cfg` are actually respected. Before, in NCPA < 2, the ncpa agent ran as root instead of nagios, which is why those commands probably worked fine.

In order for this to work with NCPA 2 you'd have to apply sudo to the command... you could add a .sudo to the end of the file and add in the `[plugin directives]` section of the `ncpa.cfg` something like:
```
.sudo = sudo $plugin_name $plugin_args
```
But I am actually not sure if that will work.

The two actual solutions (that would be better than what I just mentioned) would be:

1. If you are comfortable running the NCPA daemon as root, you can change the `uid` and `gid` values to root in your `ncpa.cfg` file and restart your services.
2. We can implement something in NCPA 2.1 that allows you to specify what plugins you would like to run through sudo, something like:
```
run_as_sudo = check_ide, check_fail2ban
```
Or something similar... because currently there is no way to run something as sudo without changing the entire way the plugins run.

**Comment by ashleydrees** [comment]
Ah.. ok, i had already added a .sudo config line to the ncpa.cfg as a way to try and get round this issue, and it is working in one location.

I do not really want to run ncpa as root (but i will if there is no other way), so i will work on this a little more now i know what will not work. and hope that 2.1 will address this issue.

**Comment by jomann09** [comment]
I will definitely add a GitHub issue to address the lack of ability to run plugins through sudo for 2.1, thanks for letting me know about the .sudo config you tried.

**Comment by Akash1602** [comment]
i am not able to list down the all running services with ncpa on remote host. please check attached screenshot.
![Capture](https://user-images.githubusercontent.com/23059122/90438150-2faf9e00-e0f1-11ea-805c-9d78a48fdaf4.JPG)
