### ISSUE TITLE
API Disk - Percent as performance data :(

### ISSUE THREAD

**Issue by metabsd** [NagiosEnterprises/ncpa#309]
It would be nice to be able to monitor on the percentage but have the performance data on the space use.

Example 1 :
./check_ncpa.py -H hostname -t 'token' -P 5693 -M 'disk/logical/|' -u M -w 90 -c 95
OK: Used disk space was 57.30 % (Used: 565.20 MB, Total_size: 1040.08 MB, Free: 421.20 MB) | 'used_percent'=57.30%;90;95;

Example 2 : 
./check_ncpa.py -H hostname-t 'token' -P 5693 -M 'disk/logical/|/used_percent' -u M -w 90 -c 95
OK: Used_percent was 57.30 % | 'used_percent'=57.30%;90;95;

Example 3 :
./check_ncpa.py -H hostname-t 'token' -P 5693 -M 'disk/logical/|/used' -u M -w 90% -c 95%
Improper warning/critical format.

Example 4 :
./check_ncpa.py -H hostname-t 'token' -P 5693 -M 'disk/logical/|/used' -u M -w 90 -c 95
CRITICAL: Used was 565.20 MB | 'used'=565.20MB;90;95;

It's sound like a feature request.

Maybe I did not understand the utility of making graphics or managing capacity on the percentage.

Thank you!!!

**Comment by jomann09** [comment]
I would agree this would probably be something we could add - it would probably need to be done on the agent side though. I will take a look later and see what we can do about it.

**Comment by jomann09** [comment]
This is done for now. We will work on making this better in the future though. Currently it'll show the % value (which is what WARN/CRIT uses) and it will give out the used, free, and total in the perfdata.

In 3, I think, we will calculate out the value for warning/critical but that won't be for a while because it requires redoing how the perfdata is written out and how the nodes work.
