### ISSUE TITLE
Document for build enviroment

### ISSUE THREAD

**Issue by varnar** [NagiosEnterprises/ncpa#32]
Is there any manual, document how to prepare build environment for  NCPA in Windows and Linux environment?

Will be nice to have - so I and another users of NCPA can do test more close to production.

Thanks

**Comment by bgshacklett** [comment]
I've just written up some documentation for building Windows and submitted pull request #200.

**Comment by jhomann** [comment]
Making a note that NCPA windows build requirements are also mentioned here https://github.com/NagiosEnterprises/ncpabuild along with some helper scripts for different environment types. I am thinking we should merge the build repo and scripts into this repo and clean it up a bit. I like your step-by-step documentation and will definitely add it in.

**Comment by bgshacklett** [comment]
Is the ncpabuild repo currently the best source for build instructions for Linux? I'd like to add a section for building on Linux to the build document at some point.

**Comment by jhomann** [comment]
I've removed the ncpabuild repo since the build requirements and scripts have been moved into the ncpa repo under the `build/scripts` section, with most of the resources that we cannot get off pip and are used with Python in the `build/resources` directory.

We will need to update the `BUILDING` file accordingly but I would also like to update the actual documentation to show it better than the text file here in GitHub.
