### ISSUE TITLE
Try to use a AIX plugin with NCPA

### ISSUE THREAD

**Issue by metabsd** [NagiosEnterprises/ncpa#347]
Hi,

I try to use check_lpar_cpu as a plugin with NCPA. Url : https://exchange.nagios.org/directory/Plugins/Operating-Systems/AIX/AIX-Native-Checks/details

It's possible to use that type of output with NCPA ? Multiline and some html tag ?

Thank you!

**Comment by jomann09** [comment]
The code looks like it would allow multi-line and in order to pass html tags you have to allow XI or Core to use tags in the output - which is a separate configuration from NCPA. We should just be passing everything that comes out of the plugin back to Nagios.

Have you tried it and has it not worked? I can test multiline and html sometime today.

**Comment by jomann09** [comment]
I tested this with just a simple check called `check_test.php` on my XI server where I had NCPA running too. I created an active check that ran the plugin. The plugin code is below:
```
#!/usr/bin/php
<?php
print "TESTING\n\nMultiline:\n<a href=\"nagios.com\">Hello World!</a>";
exit(0);
```
After setting up a check in XI and having core run the check I get the result:
![image](https://cloud.githubusercontent.com/assets/6423215/26685869/ecca9ff0-46b0-11e7-8ff3-b87329bce396.png)
I also made sure to have "Allow HTML Tags in Host/Service Status" checked in the System Settings page under Administration.

**Comment by metabsd** [comment]
I successfully use the plugin with NCPA :)

Thank you for helping :)
