### ISSUE TITLE
check_ncpa.py Centreon Entrerprise Server Standard 3.3

### ISSUE THREAD

**Issue by kimllee** [NagiosEnterprises/ncpa#360]
Hello,

Does anyone succeded to import a check from check_ncpa.py CLI mode to the Centreon's web interface ?
It perfectly works in CLI mode.
Thank you.

**Comment by jomann09** [comment]
Thanks for your interest in using NCPA!

We are really only able to help you with CLI portion when using other software and this question is probably best left up to the Centreon community rather than the users here on GitHub. I'd suggest posting this on the Centreon forums/community site and specifically ask about how you can import a set up a 3rd party plugin.
