### ISSUE TITLE
event id monitoring through NCPA

### ISSUE THREAD

**Issue by sandeependla** [NagiosEnterprises/ncpa#387]
Hello ,

How  to enable event id monitoring through NCPA.

**Comment by SlickHenry** [comment]
using check_ncpa.py as an active check you could pass the following as arg1 in addition to your token and port. This would warn if more than 3 events are found in the last 15 mins for eventID# 12345. There are several additional filters you can use as well, just comma delimit them to fit your needs.

-M 'logs/' -q 'name=System,event_id=12345,logged_after=15m,check=true,warning=3'

Documentation could be improved to show examples for check_ncpa.py since I suspect thats what many folks would use to query the agent, but it does clearly show what options are available. Docs: [https://www.nagios.org/ncpa/help.php](https://www.nagios.org/ncpa/help.php)

**Comment by jomann09** [comment]
Thanks for answering this, you are correct. I will add a note to add some more examples in the future. You can always log into the web GUI and check what that would look like in the check_ncpa.py active check format too.

**Comment by sandeependla** [comment]
Hi Henry and Jomann09,
Thanks for the reply.
In the windows server eventlog the event id is 1480. When i tried to call the information through NCPA agent it is shown the event_id as 1073743304 in API.  So NCPA will generate event_id 1073743304 for all the event id 1480 which got generated on  windows server?
![image](https://user-images.githubusercontent.com/31530012/31477725-8768599e-af2a-11e7-9df2-f79bd58ebaac.png)

**Comment by jomann09** [comment]
In NCPA < 2.0.5 the Event IDs were messed up and in the newest version they work, however you are not able to select specific Event IDs at this time due to the fact that the event_id looks like the one you are showing above. I will have a fix for the searching in the next version of NCPA. To see the proper Event IDs in the API you just need to be running NCPA 2.0.5.

**Comment by jomann09** [comment]
f3ad5e17634aa335c74fc6c300d9f3f3cbf7f93c

**Comment by jomann09** [comment]
8cb5e42986cc2391417f2258af0a77ce6412f137

**Comment by sandeependla** [comment]
Hi jomann09,

I have updated the NCPA agent 2.0.2 to 2.0.5, now i can see the event ids properly. but when i request a particular event_id it is not showing. Please find the below snips for your reference and help on this.
![capture1](https://user-images.githubusercontent.com/31530012/32310242-0396327e-bfb7-11e7-9da1-74abbd528437.JPG)
![capture2](https://user-images.githubusercontent.com/31530012/32310252-0cbfe840-bfb7-11e7-9cd3-1b30de0d8923.JPG)

.

**Comment by jomann09** [comment]
This is a known bug and is fixed in 2.0.6 which should be coming out shortly!

**Comment by sandeependla** [comment]
Hi Jomann09,

Thanks for the reply.
When can we except the next release of the ncpa agent 2.0.6.

**Comment by jomann09** [comment]
By early next week if testing goes well.

**Comment by Dipesh-tec** [comment]
@jomann09 I have Windows 2003 and on searching on internet i found that the only version of NCPA that supports this machine is 1.8.1, however i am facing an issue to get the event id data in correct format.

Any suggestion how i can get accurate data from my windows 2003 box please?
