### ISSUE TITLE
NCPA Agent for AS400

### ISSUE THREAD

**Issue by ranjithkodumbu** [NagiosEnterprises/ncpa#414]
Hi Team,

Is there any road map to develop NCPA agent for AS400/Iseries system?

Thanks,
Ranjith Kumar R

**Comment by jomann09** [comment]
Currently, no. Not only because we don't have anyone that has the knowledge about older IBM systems but also because we do not have the ability to test on one.

What operating system are you using? I did read a little bit and it says that there may be a way to use AIX binaries on IBM i, which we do build for AIX 6/7 although I wouldn't know if they would work on such systems.

In order to even build on a system we would need to be able to install some libraries and binaries such as OpenSSL, Python, and the modules for Python such as psutil. So that is also an issue, depending on if there are supported versions which work with the OS.

**Comment by jomann09** [comment]
I'm going to close this since it's not on the roadmap at this time. If you have any success with the AIX builds or you try to build it yourself, let me know!
