### ISSUE TITLE
NCPA 2.1.1 

### ISSUE THREAD

**Issue by ehoogend1** [NagiosEnterprises/ncpa#440]
I'm using NCPA 2.1.1. on Linux. I want to check the existence of a process combined with filtering. 
If the number of processes = 0 (Process not running) I want to receive a critical. Am I missing something or is this not possible?

https://<IP>:<PORT>/api/processes?username=ufm&cmd=UFM-Agent&match=search&check=true&critical=0

This returns:

{
    "returncode": 0,
    "stdout": "OK: Process count was 0 | 'process_count'=0;;0;"
}

Regards

Ed

**Comment by jomann09** [comment]
Does the actual command that is running on the system have the term `UFM-Agent` (case sensitive) and if it does what do you get in your processes list when you don't specify one to search for?

**Comment by jvandermeulen** [comment]
Hi Ed,

I knew one day I would meet you here ;-)

The goal you're trying to achieve is definitely possible! However you took the wrong turn with regards to thresholds and process filter criteria.

You entered these criteria (showing 0 processes)

> api/processes?username=ufm&cmd=UFM-Agent&match=search&check=true&critical=0

NCPA Process Filter "`cmd=`" expects everything that  `ps -u ufm -o cmd` shows as output on the command line on the server running UFM-Agent (such a full path and all arguments).
So if previous command shows "/opt/ufm/bin/UFM-Agent --daemon" you would need to add everything that sits between double quotes.

I 'd suggest to change:

- `cmd=UFM-Agent` to `name=UFM-Agent` if matching only the name of the binary is sufficient
- and `match=search` to `match=exact` because for instance UFM-AgentTest would be matched also
- and `critical=0`  to `critical=1:` as 1 match would lead to a critical. `critical=0` means critical if number of processes is greater than 0. In you case you would reverse the logic so you would have to add a colon.  `critical=1:` means critical if number of processes is less then 1.

> api/processes?username=ufm&name=UFM-Agent&match=exact&check=true&critical=1:

Regards, Jørgen van der Meulen

By the way Ed... did you find the "View in alternate format" link on the lower left part of the NCPA Gui screen? This link is very helpful in getting the right syntax for Nagios XI/Core for active/passive checks.

**Comment by ehoogend1** [comment]
Hello Jørgen,

First I want to thank everybody for responding to my question. The semicolon ':' did the thrick. I have run the check with the 1: option for critical.

https://999.999.999.999:9999/api/processes?username=ufm&username=UFM-Agent&match=search&check=true&critical=1:

{
    "returncode": 2,
    "stdout": "CRITICAL: Process count was 0 | 'process_count'=0;;1:;"
}

So this question can be closed.

Regards,

Ed
