### ISSUE TITLE
Executing "jar" plugin with ncpa

### ISSUE THREAD

**Issue by eirikrg** [NagiosEnterprises/ncpa#445]
There is any way to execute a custom jar plugin built in java with the ncpa api?
I have found a way using NSClient++ to execute jar plugins, but since I am using NCPA for monitoring windows server and I don't want to use 2 windows agents, I would like to know if there ir any way.

Thank you so much.

**Comment by ericloyd** [comment]
Yes.  But you'd have to write a script that will set up your Java environment, then execute your jar command to get your applet running, then interpret the results so that Nagios can understand them (in other words, follow the plugin API).  Then you have to do all of this within the timeout window of the NCPA plugin settings.

So it can be done, but you have to first ensure that it can be done entirely from a command line script and then wrap that script into Nagios's API format and then put it somewhere that NCPA can execute it.

Java is expensive to start each time, so I'd also be wary of executing Java-based plugins unless there's no other way.

**Comment by eirikrg** [comment]
@ericloyd Thank you for you answer. Well my plugin executed from cmd by myself is working correctly, and  Nagios can understand the results, the thing is, how do I set up the NCPA api to run a jar fine? I need to make NCPA runs something like that "java -jar plugin.jar "arg1""

**Comment by ericloyd** [comment]
No, you need to make a shell script that runs the "java -jar plugin.jar 'arg1'" command.  So you need to set up the proper JAVA_XXX variables in your script first so that it can be run without an interactive login shell.

Then you can follow the directions at https://www.nagios.org/ncpa/help.php#api-running-plugins to place your script in the Nagios plugins directory and call it via the NCPA API.

**Comment by jomann09** [comment]
You can set NCPA to recognize how to run .jar plugins by setting up a command that will run them in the `ncpa.cfg` section https://github.com/NagiosEnterprises/ncpa/blob/master/agent/etc/ncpa.cfg#L263 for plugin extensions. But as @ericloyd pointed out, you'd also need to set your environment variables so it might be worth creating a script that allows you to set those before running the plugin. You can also wrap the command that you set NCPA to use to run the plugin by calling your script.
