### ISSUE TITLE
Windows volume mount points not visible (unless mapped as drive letter)

### ISSUE THREAD

**Issue by jvandermeulen** [NagiosEnterprises/ncpa#452]
I created a new NTFS partion on allocated space and mounted it on c:\MyMountpoint following all steps described in [this TechNet ](https://technet.microsoft.com/en-us/library/cc938934.aspx) article 

To be sure I (temporary) set

> exclude_fs_types = aufs,autofs,binfmt_misc,cifs,cgroup,debugfs,devpts,devtmpfs,encryptfs,efivarfs,fuse,hugelbtfs,mqueue,nfs,overlayfs,proc,pstore,rpc_pipefs,securityfs,smb,sysfs,tmpfs,tracefs

to

> exclude_fs_types = nfs

This mountpoint remains unvisible to API endpoint 'disk' unless I attach a drive letter to it.

See also #209

**Comment by jomann09** [comment]
So for whatever reason there was a bug in the psutil version that was installed when the 2.1.3 version was built. If you'd like, you can re-download the 2.1.3 version and after upgrade you should see them appear. I am adding it to the changelog for 2.1.4 even so, since most people will probably not upgrade until the next version comes out.
