### ISSUE TITLE
NCPA for debian 6.0.5

### ISSUE THREAD

**Issue by eirikrg** [NagiosEnterprises/ncpa#453]
I have been testing ncpa succesfully to later implement it on a real debian machine, I was testing on a 9.4 debian version so I had no issues, but the thing is that the real machine is Debian 6.0.5. There is a 6+ debian release for NCPA?

**Comment by box293** [comment]
It's possible that the instructions in this KB article will work, however it's only been tested with 7.x onwards.

https://support.nagios.com/kb/article/ncpa-how-to-build-ncpa-from-source-521.html

**Comment by eirikrg** [comment]
@box293  Will try, thank you!

**Comment by jomann09** [comment]
There isn't any other way to do it. You could try to install the debian 7 version on 6 but I don't think it would work. You probably won't be able to build it on Debian 6 because the libraries available are too old. You could try a really old version of NCPA but for Debian 6 you may have to use something like NRPE.

**Comment by eirikrg** [comment]
@jomann09 Okay thank you so much. You are right, the libraries are too old to build it on Debian 6, I will try another tool!

**Comment by box293** [comment]
My only other suggestion is that you could compile those libraries from source on those systems. Starting to get pretty complicated, obviously your are stuck on Debian 6 for some specific reason so don't waste time doing stuff that may not be worthwhile in the long term.
