### ISSUE TITLE
Install NCPA without root access on Linux

### ISSUE THREAD

**Issue by ramachandran25** [NagiosEnterprises/ncpa#466]
Hi,

Is there any way to install NCPA without sudo access on Linux boxes? There are many servers which cannot provide a sudo access.

Thanks,

**Comment by jomann09** [comment]
The only part that is absolutely necessary to be ran as root is the install of the rpm because it's going to place the items in `/usr/local/ncpa` and it will add init.d configs in `/etc/init.d` ... now if you don't care about it starting on statup you could always open up the rpm file in something like 7zip and pulling out the contents that go in `/usr/local/ncpa` and placing them in that folder. You can then use `/usr/local/ncpa/ncpa_listener` to start the listener (the interface/API on <ip>:5693) and you could also run `/usr/local/ncpa/ncpa_passive` to start the passive agent.

**Comment by ramachandran25** [comment]
You are right, that is what I tried but I'm getting following error when I tried to start the listener as non root user.

2018-06-12 15:47:32,620 21078 ERROR [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/root/ncpa/agent/ncpadaemon.py", line 261, in set_uid_gid
OSError: [Errno 1] Operation not permitted

**Comment by jomann09** [comment]
It looks like the user is not able to set the uid/gid, what do you have set for the user and group in your `ncpa.cfg` file? Also, are you running as the nagios user when you're logging in?

**Comment by ramachandran25** [comment]
I set the user/group as my current user/group in ncpa.cfg. I'm running the listener as local user(non root)

**Comment by ramachandran25** [comment]
I don't see this error in NCPA version 2.0.6, is it possible to suggest me where can I change to prevent this error message? @jomann09

**Comment by jomann09** [comment]
I have not ran NCPA like that. Without looking back and digging in I don't know what the specific change was that is causing the issue. I am sure that the difference is that we are doing a few more things inside the daemon to change the user that is running it. I believe that the old NCPA (< 2.1) worked by using whatever user it was currently started as.
