### ISSUE TITLE
NCPA Support for windows 2003 servers

### ISSUE THREAD

**Issue by ramachandran25** [NagiosEnterprises/ncpa#469]
I honestly didn't know when NCPA stopped support for Windows 2003 servers, Is it possible to build a package for windows 2003 server as most of our servers are windows 2003 (these may upgrade to 2008 later).

**Comment by box293** [comment]
It's almost 3 years since Microsoft stopped supporting Server 2003, it's unlikely time will be invested in getting it to work on an old OS like this. The only suggestion I have is find the last version that worked on it and use that.

**Comment by ramachandran25** [comment]
@box293  we found one major problem that there was memory on 2.1.4 and Jake was fixed that in 2.1.5 so we need 2.1.5 version for windows 2003 server.

**Comment by senthilchokkalingam** [comment]
Windows 2003 Performance Counters with NCPA are not working. It only returns the result as 0c instead of the actual value. The NCPA agent version is 1.8.1.

The same check works fine on Windows 2008+ servers. 

Please see the example of check results on Windows 2003 servers.

[nxi01 libexec]# ./check_ncpa.py -H 10.0.0.1 -t 'token' -P 5693 -M 'windowscounters/Memory/AvailableMbytes' -w 200: -c 100:
CRITICAL: \Memory\AvailableMbytes was 0c | '\Memory\AvailableMbytes_0'=0c;200:;100:;

[nxi01 libexec]# ./check_ncpa.py -H 10.0.0.1 -t 'token' -P 5693 -M 'windowscounters/Memory/Available Mbytes' -w 200: -c 100:
CRITICAL: \Memory\Available Mbytes was 0c | '\Memory\Available Mbytes_0'=0c;200:;100:;

[nxi01 libexec]# ./check_ncpa.py -H 10.0.0.1 -t 'token' -P 5693 -M 'windowscounters/Memory/Available%20Mbytes' -w 200: -c 100:
CRITICAL: \Memory\Available%20Mbytes was 0c | '\Memory\Available%20Mbytes_0'=0c;200:;100:;

Any work around/fix please?

**Comment by jomann09** [comment]
Can you show me what the value of the windows counter is on your Windows machine?

**Comment by senthilchokkalingam** [comment]
Please see the the picture below.


[cid:image001.png@01D412A4.AF61B660]

**Comment by box293** [comment]
I do not see the screenshot.

**Comment by senthilchokkalingam** [comment]
I have attached the perfmon result and also pasted on the body as well.

[cid:image001.png@01D412FC.B2081640]

**Comment by box293** [comment]
If you are replying to these via email then it's still not working. You need to open the GitHub issue in a web browser and drag the image into the Write tab. The Preview tab will show you if it worked.

**Comment by senthilchokkalingam** [comment]
![perfmon](https://user-images.githubusercontent.com/32526987/42250140-b3e03acc-7f1e-11e8-87ab-97a50494d0be.png)

Please see the attachment

**Comment by senthilchokkalingam** [comment]
I uploaded the image and looks to be good now on the preview

**Comment by ramachandran25** [comment]
@jomann09 Can i build a new NCPA package for Redhat Linux 5.8 using the latest release?

**Comment by jomann09** [comment]
You can try but I stopped building for EL5 after the repos shut down, if you have access to an updated RHEL system then you can definitely build an rpm for it.

**Comment by jomann09** [comment]
@senthilchokkalingam Can you check your ncpa_listener.log file and see if there are errors when you use the windows counter on the system?
