### ISSUE TITLE
Request Argument Passing

### ISSUE THREAD

**Issue by scot0357** [NagiosEnterprises/ncpa#47]
As discussing in https://github.com/NagiosEnterprises/ncpa/issues/42, the variable passing scheme for the API does not allow for passing multiple values, such as:

```
api/processes/?name=bingo&name=bongo
```

Even though the backend supports this.

#### Suggested Solution

Get rid of the variadic function calls in the ```api()``` function in ```server.py```. Instead, replace this with a ```request_args=request.values```. This will require a bit of modification to the underlying tests/codes to make sure no name collisions are happening, but this will allow for greater safety and flexibility.

**Comment by scot0357** [comment]
Deferring to 1.9.0.

**Comment by jhomann** [comment]
I hooked into sane_args for this and just did a quick loop over the values that existed and wrote them out so that they are still able to be manipulated before they get to the nodes... I will add the process and service fixes to the actual nodes here at some point, maybe add a new value for "alternate name"
