### ISSUE TITLE
Symantec is blocking install of NCPA 2.1.5. (Our information on this file is inconclusive)

### ISSUE THREAD

**Issue by sampath4970** [NagiosEnterprises/ncpa#475]
Hello There,

When installing NCPA 2.1.5 on our Windows Servers, we are getting a warning from Symantec Endpoint Protection. 

Please see the attachment. 
![warning screenshot](https://user-images.githubusercontent.com/30668302/42102381-5b650242-7b8b-11e8-9680-a779366315ad.jpg)

This is definitely not a deal breaker, I can click on allow and continue. Wondering if this might cause any issue when pushed from SCCM.

Just wondering if this can be taken care by requesting for an exclusion in SEP?

Thank You,
Sampath.

**Comment by jomann09** [comment]
We actually just requested an exclusion for NCPA. We can do it again, I am not sure if they ever removed it last time because I don't think we heard back. Actually, looking at the screenshot it looks like it must have been added back in a month ago or so. I will submit another exclusion to Symantec.

As for causing issues to SCCM I am not sure, but Symantec does have instructions to create an exclusion of your own I think, but I don't have anything to test with so I don't know what the effects would be.

**Comment by jomann09** [comment]
Just a quick update I filled out the SEP exclusion form so we will see what they say.

**Comment by sampath4970** [comment]
Thank you Jake. I will go ahead and request for an exclusion until you hear back from Symantec.

**Comment by jomann09** [comment]
Just an update - they sent an email back. They have removed ncpa-2.1.5.exe from their system.
