### ISSUE TITLE
Plugins without extension

### ISSUE THREAD

**Issue by Sanantita** [NagiosEnterprises/ncpa#527]
Hi,

I have a few compiled sh plugins. Those plugins doesn't work with the ncpa.cfg for .sh files. When I call a compiled sh plugin from a http request it responses:

cannot execute binary file.

How can I run those sh compiled plugins?

Tanks!

**Comment by jvandermeulen** [comment]
@Sanantita 

The title of this issue suggests those compiled scripts have **no** extension. I tried to replicate your issue and followed these steps.

- Took a bash scripts named _check_reboot_required.bash_ and compiled it using [shc](https://github.com/neurobin/shc) like this: `shc -f check_reboot_required.bash -o check_reboot_required`
- Copied the binary check_reboot_required to the plugins folder of NCPA 2.1.6
- Prepared download/installation of check_ncpa.py plugin in current $PATH. `curl -s https://assets.nagios.com/downloads/ncpa/check_ncpa.tar.gz | tar -xz --owner=nagios -C /usr/local/bin/ check_ncpa.py`
- Used the GUI or CLI to run this plugin against the API like this: `read TOKEN; check_ncpa.py -H localhost -t ${TOKEN} -M 'plugins/check_reboot_required'`
- It turned out to be just fine, result`OK: No system reboot required`

To prove that we're running a binary: 

```
# file check_reboot_required
 check_reboot_required: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=cd89299a0abda7a6c0525f9158cb95bb3efea217, stripped
```

**Comment by jvandermeulen** [comment]
I was able to reproduce your issue after renaming `check_reboot_required.sh` to `check_reboot_required.sh`

```
# check_ncpa.py -H localhost -t ${TOKEN} -M 'plugins/check_reboot_required.sh'
/usr/local/ncpa/plugins/check_reboot_required.sh: /usr/local/ncpa/plugins/check_reboot_required.sh: cannot execute binary file
```
After providing it with another extension:
```
# mv check_reboot_required.sh check_reboot_required.bin
# check_ncpa.py -H localhost -t ${TOKEN} -M 'plugins/check_reboot_required.bin'
OK: No system reboot required
```

I suspect this configuration line is responsible for this behaviour:
```
# grep ^.sh ../etc/ncpa.cfg
.sh = /bin/sh $plugin_name $plugin_args
```
So my suggestion is to either remove the extension from the scripts or name them *.bin

**Comment by jomann09** [comment]
The above is accurate, is this issue resolved or are you still having problems with binary plugins?
