### ISSUE TITLE
Need help with the codes to address vulnerability issues

### ISSUE THREAD

**Issue by Nagios123** [NagiosEnterprises/ncpa#565]
Hi,

As per Nagios support team,  I have to modify the codes to avoid below vulnerability issues we faced during scan.
1. Autocomplete enabled for sensitive HTML form fields
2. Click Jacking
3. HTTP OPTIONS Method Enabled

can anyone help me with this, please..?

**Comment by ericloyd** [comment]
The first two sound like browser configurations.  The last one is simply to disable the OPTIONS request method in your Apache configuration.

**Comment by Nagios123** [comment]
Thank you, Eric.
for the first two issues, by any chance do you know what should be the configuration ...?

**Comment by ericloyd** [comment]
If your security team is telling you to disable browser auto-complete settings, then I would search for how to do that with whatever browser your using.

Clickjacking is something that you can't really stop, at the browser level, but then neither it is specifically a Nagios vulnerability.  Read more at https://en.wikipedia.org/wiki/Clickjacking

Disabling OPTIONS in your Apache configuration is also something you should try to find help for elsewhere.  It's not really something something specific to Nagios.

**Comment by ccztux** [comment]
As i understand those security issues refer to the webinterface of the NCPA agent. Correct me, if i am wrong.

**Comment by jomann09** [comment]
Yeah these mostly impact the web interface. For the 3rd one, as @ericloyd states it has to be turned off in the Apache configuration. For the other two:

1 - We can add `autocomplete="off"` on the form and inupts although that is definitely not something that works in every browser, can check google for complete details on what it actually does

2 - This one is harder, we can't do all that much but what we can do is send headers to tell the browser not to allow the page to load inside frames and add some javascript to "pop the page out" of the frame if it does get loaded in one.

**Comment by ccztux** [comment]
I think @Nagios123 means that the OPTIONS method of the webserver part of ncpa should be disabled:
```bash
08:53:50 [root@localhost]:~$ curl -k -i -X OPTIONS -I https://localhost:5693
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Allow: HEAD, OPTIONS, GET
Content-Length: 0
Date: Wed, 11 Sep 2019 06:54:01 GMT

```

**Comment by ericloyd** [comment]
*lol*  Hey, that makes sense! :-)

**Comment by ccztux** [comment]
Maybe [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) could also be added regarding to security.

**Comment by jomann09** [comment]
The way flask/gevent's server is working in NCPA, you cannot actually connect via http so that shouldn't be required. I do see that flask automatically adds the OPTIONS values to every request. It looks like there's not a good way to disable them without doing some changes to every section.

**Comment by jomann09** [comment]
Coming back to look into these with a few findings:

- A note on HSTS. I don't think HSTS is necessary here, from my understanding, since we don't even serve NCPA over anything but HTTPS - you cannot connect via HTTP at all. We don't load anything from external links either.

-  I can't find a good way to disable OPTIONS for Flask, if anyone else has a way to do it please let me know. From looking into this more, besides telling you what is already available via the sourcecode (if anyone wants to see what we accept it's in the server.py) but the only vulnerabilities related to code are in Apache, and we aren't using Apache here.

- I have added the `autocomplete="off"` parameter to the login for the web UI and for the admin section of the web UI when there is an admin password set.

- I have added X-Frame-Options and Content-Security-Policy options to the headers by default and added an ncpa.cfg called allowed_sources which edits these options to allow NCPA in a frame for certain locations if someone wants to use it in a frame.

I am going to close this considering I've done what I can do for now and the rest are likely not things we are going to be able to do. The things above that I mentioned adding will be in the 2.1.10 version.

**Comment by jomann09** [comment]
One more update, this'll be in 2.2.0 which will be the next version now since we have quite a few enhancements going into it.
