### ISSUE TITLE
Question: Where do you publish check_ncpa.py releases/updates??

### ISSUE THREAD

**Issue by Guyver1wales** [NagiosEnterprises/ncpa#594]
So based on the feedback so far from my services with $ sign issue it appears I'm still using check_ncpa.py v1.1.5 whereas the latest version is 1.2.0.

However, I do not appear to be getting any releases email notifications for this?
Do I only get release emails for the actual NCPA client updates?

What is the update cycle for check_ncpa.py? Does it get updated whenever ncpa gets updated or is it on its own update path separate to NCPA? How can i get notified of check_ncpa.py updates??

One other to mention, I just updated my Nagios XI lab installation from 5.6.7 to 5.6.8 and the check_ncpa.py version was still 1.1.5 so it appears that the check_ncpa.py plugin is not being updated when Nagios XI is being updated. Given that nagios XI has NCPA natively built in, I am a bit puzzled as to why the plugin isn't being updated??

**Comment by jomann09** [comment]
So the issue is that the check_ncpa.py client isn't it's own project it's part of this repo and it sometimes gets updated between NCPA releases so it's kind of a separate entity. We don't have a specific release for just the client. The client normally isn't updated that often however, compared to the actual agent.

As far as the Nagios XI update, we typically let the client go out for a couple weeks before we add it into the wizard because we want to ensure that we didn't miss any issues. As it happens the new wizard was in the testing queue and I have pushed it up so the 1.2.0 version of the client should come out today in the NCPA wizard 2.2.1.

**Comment by jomann09** [comment]
Going to also point out that it's changelog and updates are available here: https://github.com/NagiosEnterprises/ncpa/blob/master/client/CHANGES.rst

And also mention here that the NCPA wizard should be updated now in XI and you should be able to run the check for updates on the config wizard page and update your wizard for the new plugin.
