### ISSUE TITLE
Missing service behaviour - multiple service check

### ISSUE THREAD

**Issue by SheffSix** [NagiosEnterprises/ncpa#600]
When checking multiple services, and one of the services specified doesn't exist, the API responds OK and does not include the missing service in the check. I would expect that the check should at least report UNKNOWN at this point, if not CRITICAL.

This could be an issue if, for example, a vendor changes the name of a service in an update, or a service get inadvertently uninstalled.

Passive plugin def example:
`%HOSTNAME%|Production Services = services?service=NonExtistantService1&service=Service2&service=Service3&service=Service4&service=Service5&status=running`

Returns:
`{
    "returncode": 0,
    "stdout": "OK: Service2 is running, Service3 is running, Service4 is running, Service5 is running"
}`

NCPA 2.2.0
Tested on Windows Server 2012 R2, Server 2016, and Ubuntu Server 16.04

**Comment by jomann09** [comment]
I'm adding this into the next version, because it makes a lot of sense and should be doing that already. The way it is built currently, it doesn't even care if it doesn't find values for services. I did a bit of a hacky fix to make this work for this version since NCPA 3 this section will (hopefully) be rewritten.
