### ISSUE TITLE
Have an option to disable alerts if a host is shutdown gracefully. 

### ISSUE THREAD

**Issue by CaptainWowWee** [NagiosEnterprises/ncpa#707]
Could you please add a feature that allows servers that are shutdown gracefully not to alert in Nagios.

Then also have the option to continue to monitor these servers once they are brought back on-line. 

In lots of cloud based environments server usage is kept to a minimum to lower costs and this feature would be very useful.

Thank you so much.

Stephen P

**Comment by ericloyd** [comment]
This can be done with passive commands (via NRDP) sent to Nagios as part of the machine's shutdown/startup processes to cease Nagios alerts for that host (or to schedule downtime for it) and to reverse that when the machine starts up.

Otherwise, this is simply not how Nagios works.  You would require an agent on every box that is aware of shutdown/startup procedures (as opposed to agent start/stop procedures) and this is not a manageable solution. 

You will want to look at scheduled downtime, in any event, as this is the supported method for doing what you want, it's just not automated exactly as you want.  That's where the NRDP option comes in.

**Comment by jomann09** [comment]
I agree with @ericloyd on this, ideally you'd have to set up an NRDP command that would set some sort of downtime to actually make this work the way you are thinking. Alternatively if you're using Nagios XI you could also send off an API call that would remove the host from your system, however if this happens really frequently it might be better to just scheduled a downtime instead to avoid the apply configurations.

**Comment by CaptainWowWee** [comment]
Thank you both for your feedback.

Apologies for the delayed response.

I will look into this I am very experienced in Nagios so your advice is very helpful.

Thank you very much.

Stephen P

________________________________

**Comment by jomann09** [comment]
No problem, closing this as we won't be adding it.
