### ISSUE TITLE
Passive Checks Specific Duration Per Check

### ISSUE THREAD

**Issue by scot0357** [NagiosEnterprises/ncpa#74]
Add specific durations for specific checks. IE, we want to run one check every minute and some other check every five minutes. Current syntax:

```%hostname%|%servicename% = check```

Suggested syntax:

```%hostname%|%servicename%|%duration = check```

Where the duration is optional, and if not specified will fallback to the global sleep directive.

**Comment by jhomann** [comment]
Potential issue with this that might cause it to be pushed back out of 2.0.0 is that the current way passive checks work, it sleeps the entire passive check process until the next check is ran. We would need to leave the passive check running and sleep it for 1 second between checks. Each time it "wakes up" it would need to verify that no checks should be processed and then go back to sleep.

I'm wondering if this will have any performance decrease on the system since it will be doing a lot more than it was before.

**Comment by jomann09** [comment]
This is a bit harder than I thought it would be due to how the passive check system was implemented. However, I am currently just testing out a version of this right now and so far it seems to be going well. I will most likely have it working tomorrow - which should wrap up the 2.0.0 changes.

**Comment by jomann09** [comment]
This has been added in c40096e4cedaa58e7edef71a5e7bf8918391d3fd
