### ISSUE TITLE
ERROR an integer is required on max_connections configuration

### ISSUE THREAD

**Issue by dorancemc** [NagiosEnterprises/ncpa#812]
On update parameter max_connections, after restart I got the error: 

```
ERROR an integer is required
Traceback (most recent call last):
  File "ncpa_listener.py", line 109, in run
  File "/usr/local/lib/python2.7/site-packages/gevent/pool.py", line 681, in __init__
  File "src/gevent/_semaphore.py", line 32, in gevent._semaphore.Semaphore.__init__ (src/gevent/gevent._semaphore.c:1389)
TypeError: an integer is required
```

- Debian/buster: ncpa/2.3.1-1 amd64 
- RHEL/8 : ncpa-2.3.1-1.el8.x86_64

**Comment by ccztux** [comment]
Thats interesting. Can you please provide the output of the following command?:
```
grep max_connections /usr/local/ncpa/etc/ncpa.cfg
```

**Comment by dorancemc** [comment]
Hello, this is the output:
```
grep max_connections /usr/local/ncpa/etc/ncpa.cfg
max_connections = 100
```

**Comment by ccztux** [comment]
Thanks for providing the output of the command.
The issue seems to be the missing typecasting to integer when getting the configuration value. I will provide a fix via a pull request.
As a workaround you can comment the `max_connections` configuration directive and restart the `ncpa_listener` service. I think this should work. The `max_connections` will fall back to its default value of `200`.

**Comment by dorancemc** [comment]
Thank you, we already had commented this parameter.

**Comment by ccztux** [comment]
You are welcome!
Has it worked?

**Comment by dorancemc** [comment]
Yes, is working for now, we want to limit the connections in the future. Thanks for your help.

**Comment by ccztux** [comment]
Thank you for your response!

**Comment by jomann09** [comment]
Fixed with merge request so closing this.
