### ISSUE TITLE
AIX, logical disk check issue after 16 TB, latest build timeline delays

### ISSUE THREAD

**Issue by k17034** [NagiosEnterprises/ncpa#833]
Hello. I've recently run into an issue with AIX logical disk check, after crossing 16 TB boundary, using "latest" available NCPA for AIX v.  2.2.1 (released February 2020).

From looking at the commercial Nagios support forums, another customer had the issue, and the Nagios Support guidance was to open an issue here.  That was done, and issue remains open here: https://github.com/NagiosEnterprises/ncpa/issues/797

Also, from looking at closed issues here, it would appear that AIX NCPA builds are delayed (abandoned?) due to availability of AIX build resources: https://github.com/NagiosEnterprises/ncpa/issues/676

Is development/support for latest AIX NCPA still ongoing?

Can we get an update?

Thanks.

**Comment by jomann09** [comment]
Development is still ongoing, you are right though that we do not have prolonged access to AIX to build against, and until NCPA 3 is released/finished we probably won't build on it due to python 2.7 builds not working very well the way we build/freeze the python code for deployment.

We are currently working on NCPA 3 deployment/building so we should have more updates coming.

**Comment by jomann09** [comment]
Closing this since we will handle the AIX issue with #797
