### ISSUE TITLE
Question: Running NCPA inside a container.

### ISSUE THREAD

**Issue by metabsd** [NagiosEnterprises/ncpa#848]
Would it be possible to run NCPA in a container to be able to monitor certain services like DNS queries or network performance tests.

Thank you!

**Comment by ericloyd** [comment]
Welllll, you could run it in a container, but the container would be the thing reporting status, not the host system.  So that is not likely what you want.  If you just want a worker that does work, then you're more likely interested in mod_gearman.  NCPA is an agent designed to be installed on the machine that you're going to be querying for information.

**Comment by metabsd** [comment]
I'm trying to think of a solution that would allow me to run context monitoring of Openshift. So I was thinking of running a container agent in Openshift to collect DNS and Speedtest metrics.

**Comment by ericloyd** [comment]
NCPA can run in most any *ix or Windows environment.  So you could certainly run it in a container.  But it would be limited to seeing what that container is allowed to see, so I'm not sure the benefit of doing so.  Plus, it's not really a "hey, NCPA, go run this command for me" type thing.  If you want to do that, SSH is better, and if you want to make it scale, mod_gearman is even more better.

But nothing's stopping you from installing NCPA in a container, exposing port 5693 (or whatever port you use) and then connecting to it and having it run modules that check stuff.

**Comment by metabsd** [comment]
Thx, I will explore the mod_gearman option.
