### ISSUE TITLE
NCPA Agent issue in AIX 

### ISSUE THREAD

**Issue by dthapar1088** [NagiosEnterprises/ncpa#876]
NCPA Agent is installed on our Aix environment to monitor our IBM Virtual Server, and functionality like AIX services, and processes are not showing while configuring the host on Nagios XI. 
we have 3 different instances installed and they work completely ok but with this one, we do not see many features. 
below services are active in Aix 
ncpa_listener
ncpa_passive

Attaching the Screen shot of the error. 
Thanks !! 

[NCPA error.docx](https://github.com/NagiosEnterprises/ncpa/files/8925380/NCPA.error.docx)

**Comment by jomann09** [comment]
Is there something special running on the system that isn't working? Generally if an API endpoint is not showing up it's due to an error when trying to gather the information from the system. You can check in `/usr/local/ncpa/var/log/ncpa_listener.log` for any errors that might be happening when you're trying to access the services.

That being said we haven't been able to test/build on AIX for a while now due to not having access to a server. We do plan to at some point get AIX builds going again in NCPA 3 at some point.

**Comment by jomann09** [comment]
Closing this as no response.
