### ISSUE TITLE
French System and UTF-8

### ISSUE THREAD

**Issue by cch2107** [NagiosEnterprises/ncpa#895]
Dear,
Can we hope to have soon the 3.0 version ?
We can't use NCPA with french system because of the problem with UTF-8

[https://github.com/NagiosEnterprises/ncpa/issues/770](url)

Regards,

**Comment by sawolf** [comment]
Hi @cch2107, thanks for reaching out.

I can't give you a timeframe, but I can say that NCPA 3.0 is definitely still coming. 

I'm going to close this issue since it's similar to several existing issues (#439 #608 #770), some of which are included in the 3.0 milestone. Feel free to continue discussion there if needed.
