### ISSUE TITLE
Create Data for Web Page on Host

### ISSUE THREAD

**Issue by cydo67** [NagiosEnterprises/ncpa#91]
What do I need to know in order to add custom data on the web page for NCPA on a host. I am working with a company that wants to add serveral custom graphics for data on the web page.

I can see in the source that there are several functions that create the current data. Can I just write a custom function and add it to this page:

Code: Select all
    function load_interface() {
        var interface_div = $('#interface');
        var INTERFACE_API = '/api/interface/';
        var INTERFACE_BASE = '/graph/interface/';
        var metrics = ['bytes_recv', 'bytes_sent'];
       
        $.getJSON(INTERFACE_API, function(d) {
            $.each(d.value['interface'], function(key) {
                var sent = INTERFACE_BASE + key + '/bytes_sent?delta=1&unit=K';
                var recv = INTERFACE_BASE + key + '/bytes_recv?delta=1&unit=K';
                interface_div.append($('<div>').load(sent));
                interface_div.append($('<div>').load(recv));
            })
        })
    }

Any information on what I need to do would be helpful....

**Comment by jhomann** [comment]
I'm not sure if scot's answer was sufficient but yes you can edit the static directory to write custom code to manage the graphs.

Since this issue has two different items in it and Nick added a separate issue for the one I am going to close this for now since I am unable to determine what needs to be done for this to work.

Please create another issue if you'd like make a feature request, and give us as much information as possible! Thanks!
