### ISSUE TITLE
NCPA 2.4.1 release - status for OpenSSL fixes

### ISSUE THREAD

**Issue by MrPippin66** [NagiosEnterprises/ncpa#920]
Which specific OpenSSL version was bundled in the 2.4.1 release?

There had been a CVE against it which might not have been included in the 2.4.0 release, but hopefully resolved in the 2.4.1 release.

If so, can the release notes be updated to include the CVE?

**Comment by corynorell** [comment]
Thank you for bringing this to our attention. We are going to start working on investigating and remediating this now. We will have a solution in the next patch release (2.4.2), to be released ASAP.

**Comment by sawolf** [comment]
Hey guys - I'm taking over on this project for the time being.
I want to clarify and expand on the Cory's response above so that everyone's on the same page:

> There had been a CVE against it which might not have been included in the 2.4.0 release, but hopefully resolved in the 2.4.1 release.

This part we're probably not addressing immediately - I'll try to look into it soon but that might have been dependent on Python 3 somehow, in which case it definitely won't happen until NCPA 3. Unfortunately I can't commit to a timeline there either way.

> Comparing the openssl versions of 2.4.0 and 2.4.1 I found this:

> ncpa-2.4.0.el9.x86_64.rpm:
libssl.so.3.0.1-3.0.1-38.el9.x86_64.debug

> ncpa-2.4.1.el9.x86_64.rpm:
libssl.so.1.0.2k.debug

This is what we're addressing ASAP - it may or not be 2.4.2, depending on whether we have to make changes to NCPA's actual source code, but there should be another release coming shortly regardless.

While I'm here I'm also going to address:
> I'd argue then that 2.4.1 is not a security release

We're calling it a security release because CVE-2023-24037 was filed against NCPA 2.4.0 and earlier, and we addressed it in the 2.4.1 release. I agree that it doesn't address the concern from the other issue. I do think there's at least one issue open related to old OpenSSL, but I'm not going to dig for it right now - @corynorell and I talked, I'm leaving this one open until we're sure the opening post's concerns are addressed or they're duplicated by another open issue.

> So the openssl library must have been manually placed in the package
Close, but not quite - if you look into BUILDING.rst, you might find it informative. Phred found that the build process for el9 "succeeded" when built on el9, but after install there were a bunch of issues. He then found that building on CentOS 7 (with some changes, see el9-ncpa.spec) produced a working build for CentOS 9, so that's what was shipped. It didn't register for me that the system OpenSSL was getting bundled into NCPA, and that that was the main issue with building - that's my mistake.

but yes, TL;DR, the OpenSSL that's in the NCPA RPMs is the latest OpenSSL for CentOS 7, regardless of which distro you're installing it on at the moment.

**Comment by sawolf** [comment]
> What I meant to say, but didn't make clear enough, is that everyone who sees the security release will probably silently assume that all security related issues were fixed...

That's totally fair, I can see your point. There are multiple people now working on NCPA 3 (not including myself) so we can get this situation resolved properly.

> Regarding python 2.7 and OpenSSL 3.0.1 in CentOS 9...

So, the current issue I'm running into is almost identical to #868, except for the distribution. To me, that leaves an open question of how 2.4.0 was successfully released with libssl 3 on CentOS 9, but the suggestion you have to resolve it is very close to what Jake did to handle #868.

My current plan is to rebuild NCPA 2.4.1 with OpenSSL 1.1.1t as a stopgap measure (if that's successful, we'll have a 2.4.1-2 out early next week at the latest), and we'll put our efforts to getting NCPA 3 out as soon as possible.

**Comment by sawolf** [comment]
Hey guys, I got a working RPM build with OpenSSL 1.1.1t and zlib 1.2.13 - you can download it from https://assets.nagios.com/downloads/ncpa/nightly/ncpa-2.4.1-2.el9.x86_64.rpm or https://assets.nagios.com/downloads/ncpa/nightly/ncpa-2.4.1-2.el7.x86_64.rpm if you'd like to test it yourself. Otherwise, we'll officially update our repos once QA signs off on it.

> RHEL 7.9 OpenSSL 1.0.2, then it might very well include all necessary current CVE fixes - you'd have to check.

Unfortunately, for the OpenSSL-related CVEs (CVE-2011-1473, CVE-2011-5094), RHEL listed it as "won't fix" for RHEL 4/5/6 (this was before RHEL 7 came out). For the zlib issue (CVE-2022-37434), Red Hat listed RHEL 7 as "affected" but didn't indicate anything about a fix (RHEL 8 and 9 are already patched).

**Comment by MrPippin66** [comment]
NCPA isn't available for RHEL versions less than 7, anyway. Not a big deal. RHEL7 is the prime version we'd want addressed.

**Comment by corynorell** [comment]
To close the loop on this one, those packages were updated when Sebastian found the fix. We didn't bump the version because we only updated a dependency.
